/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppPlaylistsRouteImport } from './routes/_app/playlists'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStatsRouteImport } from './routes/_app/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connect': typeof ConnectRoute
  '/history': typeof AppHistoryRoute
  '/playlists': typeof AppPlaylistsRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connect': typeof ConnectRoute
  '/history': typeof AppHistoryRoute
  '/playlists': typeof AppPlaylistsRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/connect': typeof ConnectRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/playlists': typeof AppPlaylistsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/connect'
    | '/history'
    | '/playlists'
    | '/settings'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/connect'
    | '/history'
    | '/playlists'
    | '/settings'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/callback'
    | '/connect'
    | '/_app/history'
    | '/_app/playlists'
    | '/_app/settings'
    | '/_app/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists': {
      id: '/_app/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppPlaylistsRoute: typeof AppPlaylistsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppPlaylistsRoute: AppPlaylistsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
