/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppPlayerRouteImport } from './routes/_app/player'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppPlaylistsIndexRouteImport } from './routes/_app/playlists.index'
import { Route as AppPlaylistsPlaylistIdRouteImport } from './routes/_app/playlists.$playlistId'
import { Route as AppPlaylistsNewRouteImport } from './routes/_app/playlists.new'
import { Route as AppTracksIndexRouteImport } from './routes/_app/tracks/index'
import { Route as AppTracksTrackIdRouteImport } from './routes/_app/tracks/$trackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerRoute = AppPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsIndexRoute = AppPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsPlaylistIdRoute = AppPlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsNewRoute = AppPlaylistsNewRouteImport.update({
  id: '/playlists/new',
  path: '/playlists/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTracksIndexRoute = AppTracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => AppRoute,
} as any)
const AppTracksTrackIdRoute = AppTracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connect': typeof ConnectRoute
  '/history': typeof AppHistoryRoute
  '/import': typeof AppImportRoute
  '/player': typeof AppPlayerRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/playlists/$playlistId': typeof AppPlaylistsPlaylistIdRoute
  '/playlists/new': typeof AppPlaylistsNewRoute
  '/tracks/$trackId': typeof AppTracksTrackIdRoute
  '/playlists/': typeof AppPlaylistsIndexRoute
  '/tracks/': typeof AppTracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/connect': typeof ConnectRoute
  '/history': typeof AppHistoryRoute
  '/import': typeof AppImportRoute
  '/player': typeof AppPlayerRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/playlists/$playlistId': typeof AppPlaylistsPlaylistIdRoute
  '/playlists/new': typeof AppPlaylistsNewRoute
  '/tracks/$trackId': typeof AppTracksTrackIdRoute
  '/playlists': typeof AppPlaylistsIndexRoute
  '/tracks': typeof AppTracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/connect': typeof ConnectRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/import': typeof AppImportRoute
  '/_app/player': typeof AppPlayerRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/playlists/$playlistId': typeof AppPlaylistsPlaylistIdRoute
  '/_app/playlists/new': typeof AppPlaylistsNewRoute
  '/_app/tracks/$trackId': typeof AppTracksTrackIdRoute
  '/_app/playlists/': typeof AppPlaylistsIndexRoute
  '/_app/tracks/': typeof AppTracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/connect'
    | '/history'
    | '/import'
    | '/player'
    | '/search'
    | '/settings'
    | '/stats'
    | '/playlists/$playlistId'
    | '/playlists/new'
    | '/tracks/$trackId'
    | '/playlists/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/connect'
    | '/history'
    | '/import'
    | '/player'
    | '/search'
    | '/settings'
    | '/stats'
    | '/playlists/$playlistId'
    | '/playlists/new'
    | '/tracks/$trackId'
    | '/playlists'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/callback'
    | '/connect'
    | '/_app/history'
    | '/_app/import'
    | '/_app/player'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/stats'
    | '/_app/playlists/$playlistId'
    | '/_app/playlists/new'
    | '/_app/tracks/$trackId'
    | '/_app/playlists/'
    | '/_app/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player': {
      id: '/_app/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AppPlayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/': {
      id: '/_app/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof AppPlaylistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/$playlistId': {
      id: '/_app/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof AppPlaylistsPlaylistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/new': {
      id: '/_app/playlists/new'
      path: '/playlists/new'
      fullPath: '/playlists/new'
      preLoaderRoute: typeof AppPlaylistsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracks/': {
      id: '/_app/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof AppTracksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracks/$trackId': {
      id: '/_app/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof AppTracksTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppImportRoute: typeof AppImportRoute
  AppPlayerRoute: typeof AppPlayerRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppPlaylistsPlaylistIdRoute: typeof AppPlaylistsPlaylistIdRoute
  AppPlaylistsNewRoute: typeof AppPlaylistsNewRoute
  AppTracksTrackIdRoute: typeof AppTracksTrackIdRoute
  AppPlaylistsIndexRoute: typeof AppPlaylistsIndexRoute
  AppTracksIndexRoute: typeof AppTracksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppImportRoute: AppImportRoute,
  AppPlayerRoute: AppPlayerRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppPlaylistsPlaylistIdRoute: AppPlaylistsPlaylistIdRoute,
  AppPlaylistsNewRoute: AppPlaylistsNewRoute,
  AppTracksTrackIdRoute: AppTracksTrackIdRoute,
  AppPlaylistsIndexRoute: AppPlaylistsIndexRoute,
  AppTracksIndexRoute: AppTracksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
