-- MusicBrainz's genre list (CC0), from src/data/musicbrainz-genres.json by scripts/genres.ts.
INSERT INTO "genres" ("name", "key") VALUES
  ('2 tone', '2tone'),
  ('2-step', '2step'),
  ('3-step', '3step'),
  ('aak', 'aak'),
  ('abhang', 'abhang'),
  ('aboio', 'aboio'),
  ('abstract hip hop', 'abstracthiphop'),
  ('acholitronix', 'acholitronix'),
  ('acid breaks', 'acidbreaks'),
  ('acid house', 'acidhouse'),
  ('acid jazz', 'acidjazz'),
  ('acid rock', 'acidrock'),
  ('acid techno', 'acidtechno'),
  ('acid trance', 'acidtrance'),
  ('acidcore', 'acidcore'),
  ('acousmatic', 'acousmatic'),
  ('acoustic blues', 'acousticblues'),
  ('acoustic chicago blues', 'acousticchicagoblues'),
  ('acoustic rock', 'acousticrock'),
  ('acoustic texas blues', 'acoustictexasblues'),
  ('adhunik geet', 'adhunikgeet'),
  ('afoxê', 'afoxe'),
  ('african blues', 'africanblues'),
  ('afro house', 'afrohouse'),
  ('afro rock', 'afrorock'),
  ('afro trap', 'afrotrap'),
  ('afro-cuban jazz', 'afrocubanjazz'),
  ('afro-funk', 'afrofunk'),
  ('afro-jazz', 'afrojazz'),
  ('afro-zouk', 'afrozouk'),
  ('afrobeat', 'afrobeat'),
  ('afrobeats', 'afrobeats'),
  ('afropiano', 'afropiano'),
  ('afroswing', 'afroswing'),
  ('agbadza', 'agbadza'),
  ('agbekor', 'agbekor'),
  ('aggrotech', 'aggrotech'),
  ('agronejo', 'agronejo'),
  ('ahwash', 'ahwash'),
  ('aita', 'aita'),
  ('akishibu-kei', 'akishibukei'),
  ('al jeel', 'aljeel'),
  ('aleke', 'aleke'),
  ('algerian chaabi', 'algerianchaabi'),
  ('algorave', 'algorave'),
  ('alloukou', 'alloukou'),
  ('alpenrock', 'alpenrock'),
  ('alté', 'alte'),
  ('alternative country', 'alternativecountry'),
  ('alternative dance', 'alternativedance'),
  ('alternative folk', 'alternativefolk'),
  ('alternative hip hop', 'alternativehiphop'),
  ('alternative metal', 'alternativemetal'),
  ('alternative pop', 'alternativepop'),
  ('alternative punk', 'alternativepunk'),
  ('alternative r&b', 'alternativerandb'),
  ('alternative rock', 'alternativerock'),
  ('amapiano', 'amapiano'),
  ('ambasse bey', 'ambassebey'),
  ('ambient', 'ambient'),
  ('ambient americana', 'ambientamericana'),
  ('ambient dub', 'ambientdub'),
  ('ambient house', 'ambienthouse'),
  ('ambient noise wall', 'ambientnoisewall'),
  ('ambient plugg', 'ambientplugg'),
  ('ambient pop', 'ambientpop'),
  ('ambient techno', 'ambienttechno'),
  ('ambient trance', 'ambienttrance'),
  ('ambrosian chant', 'ambrosianchant'),
  ('american gamelan', 'americangamelan'),
  ('american primitive guitar', 'americanprimitiveguitar'),
  ('americana', 'americana'),
  ('amigacore', 'amigacore'),
  ('anarcho-punk', 'anarchopunk'),
  ('anatolian rock', 'anatolianrock'),
  ('andalusian classical', 'andalusianclassical'),
  ('andean new age', 'andeannewage'),
  ('anglican chant', 'anglicanchant'),
  ('animal sounds', 'animalsounds'),
  ('anti-folk', 'antifolk'),
  ('aor', 'aor'),
  ('apala', 'apala'),
  ('appalachian folk', 'appalachianfolk'),
  ('aquacrunk', 'aquacrunk'),
  ('arabesk', 'arabesk'),
  ('arabesk rap', 'arabeskrap'),
  ('arena rock', 'arenarock'),
  ('arrocha', 'arrocha'),
  ('arrocha funk', 'arrochafunk'),
  ('arrocha sertanejo', 'arrochasertanejo'),
  ('arrochadeira', 'arrochadeira'),
  ('ars antiqua', 'arsantiqua'),
  ('ars nova', 'arsnova'),
  ('ars subtilior', 'arssubtilior'),
  ('art pop', 'artpop'),
  ('art punk', 'artpunk'),
  ('art rock', 'artrock'),
  ('art song', 'artsong'),
  ('artcore', 'artcore'),
  ('ashkenazi cantorial music', 'ashkenazicantorialmusic'),
  ('asian rock', 'asianrock'),
  ('asmr', 'asmr'),
  ('assiko', 'assiko'),
  ('atmospheric black metal', 'atmosphericblackmetal'),
  ('atmospheric drum and bass', 'atmosphericdrumandbass'),
  ('atmospheric sludge metal', 'atmosphericsludgemetal'),
  ('audio documentary', 'audiodocumentary'),
  ('audio drama', 'audiodrama'),
  ('autonomic', 'autonomic'),
  ('avant-folk', 'avantfolk'),
  ('avant-garde', 'avantgarde'),
  ('avant-garde jazz', 'avantgardejazz'),
  ('avant-garde metal', 'avantgardemetal'),
  ('avant-garde pop', 'avantgardepop'),
  ('avant-prog', 'avantprog'),
  ('avanzada', 'avanzada'),
  ('avtorskaya pesnya', 'avtorskayapesnya'),
  ('axé', 'axe'),
  ('bacardi', 'bacardi'),
  ('bachata', 'bachata'),
  ('bachatón', 'bachaton'),
  ('bagad', 'bagad'),
  ('bagatelle', 'bagatelle'),
  ('baguala', 'baguala'),
  ('baião', 'baiao'),
  ('baila', 'baila'),
  ('baisha xiyue', 'baishaxiyue'),
  ('baithak gana', 'baithakgana'),
  ('bakersfield sound', 'bakersfieldsound'),
  ('balani show', 'balanishow'),
  ('balearic beat', 'balearicbeat'),
  ('balearic trance', 'balearictrance'),
  ('balinese gamelan', 'balinesegamelan'),
  ('balitaw', 'balitaw'),
  ('ballad', 'ballad'),
  ('ballad opera', 'balladopera'),
  ('ballet', 'ballet'),
  ('ballet de cour', 'balletdecour'),
  ('ballroom house', 'ballroomhouse'),
  ('baltimore club', 'baltimoreclub'),
  ('bambuco', 'bambuco'),
  ('banda sinaloense', 'bandasinaloense'),
  ('bandari', 'bandari'),
  ('bandinha', 'bandinha'),
  ('banga', 'banga'),
  ('bantengan', 'bantengan'),
  ('baqashot', 'baqashot'),
  ('barber beats', 'barberbeats'),
  ('barbershop', 'barbershop'),
  ('bard rock', 'bardrock'),
  ('bardcore', 'bardcore'),
  ('baroque', 'baroque'),
  ('baroque pop', 'baroquepop'),
  ('baroque suite', 'baroquesuite'),
  ('bashment soca', 'bashmentsoca'),
  ('bass house', 'basshouse'),
  ('bassline', 'bassline'),
  ('batida', 'batida'),
  ('batidão romântico', 'batidaoromantico'),
  ('batonebi songs', 'batonebisongs'),
  ('battle rap', 'battlerap'),
  ('battle record', 'battlerecord'),
  ('batucada', 'batucada'),
  ('batuque', 'batuque'),
  ('baul gaan', 'baulgaan'),
  ('beach music', 'beachmusic'),
  ('beat bolha', 'beatbolha'),
  ('beat bruxaria', 'beatbruxaria'),
  ('beat fino', 'beatfino'),
  ('beat music', 'beatmusic'),
  ('beat poetry', 'beatpoetry'),
  ('beat rock', 'beatrock'),
  ('beatboxing', 'beatboxing'),
  ('beatdown hardcore', 'beatdownhardcore'),
  ('bebop', 'bebop'),
  ('bedoui wahrani', 'bedouiwahrani'),
  ('bedroom pop', 'bedroompop'),
  ('beijing opera', 'beijingopera'),
  ('bélé', 'bele'),
  ('belgian techno', 'belgiantechno'),
  ('bend-skin', 'bendskin'),
  ('beneventan chant', 'beneventanchant'),
  ('benga', 'benga'),
  ('beni', 'beni'),
  ('benna', 'benna'),
  ('beompae', 'beompae'),
  ('bérite club', 'beriteclub'),
  ('berlin school', 'berlinschool'),
  ('bhajan', 'bhajan'),
  ('bhangra', 'bhangra'),
  ('bhavageethe', 'bhavageethe'),
  ('bhojpuri pop', 'bhojpuripop'),
  ('big band', 'bigband'),
  ('big beat', 'bigbeat'),
  ('big room house', 'bigroomhouse'),
  ('big room trance', 'bigroomtrance'),
  ('biguine', 'biguine'),
  ('bikutsi', 'bikutsi'),
  ('binaural beats', 'binauralbeats'),
  ('biraha', 'biraha'),
  ('birdsong', 'birdsong'),
  ('birmingham sound', 'birminghamsound'),
  ('bit music', 'bitmusic'),
  ('bitpop', 'bitpop'),
  ('black ''n'' roll', 'blacknroll'),
  ('black ambient', 'blackambient'),
  ('black metal', 'blackmetal'),
  ('black midi', 'blackmidi'),
  ('black noise', 'blacknoise'),
  ('blackened crust', 'blackenedcrust'),
  ('blackened death metal', 'blackeneddeathmetal'),
  ('blackgaze', 'blackgaze'),
  ('bleep techno', 'bleeptechno'),
  ('blue-eyed soul', 'blueeyedsoul'),
  ('bluegrass', 'bluegrass'),
  ('bluegrass gospel', 'bluegrassgospel'),
  ('blues', 'blues'),
  ('blues rock', 'bluesrock'),
  ('bocet', 'bocet'),
  ('boduberu', 'boduberu'),
  ('boedra', 'boedra'),
  ('bogino duu', 'boginoduu'),
  ('bolero', 'bolero'),
  ('bolero español', 'boleroespanol'),
  ('bolero son', 'boleroson'),
  ('bolero-beat', 'bolerobeat'),
  ('bomba', 'bomba'),
  ('bomba del chota', 'bombadelchota'),
  ('bongo flava', 'bongoflava'),
  ('boogaloo', 'boogaloo'),
  ('boogie', 'boogie'),
  ('boogie rock', 'boogierock'),
  ('boogie-woogie', 'boogiewoogie'),
  ('boom bap', 'boombap'),
  ('bossa nova', 'bossanova'),
  ('bounce', 'bounce'),
  ('bounce beat', 'bouncebeat'),
  ('bouncy techno', 'bouncytechno'),
  ('bouyon', 'bouyon'),
  ('boyfriend country', 'boyfriendcountry'),
  ('brass band', 'brassband'),
  ('brazilian bass', 'brazilianbass'),
  ('brazilian phonk', 'brazilianphonk'),
  ('break-in', 'breakin'),
  ('breakbeat', 'breakbeat'),
  ('breakbeat hardcore', 'breakbeathardcore'),
  ('breakbeat kota', 'breakbeatkota'),
  ('breakcore', 'breakcore'),
  ('breaks', 'breaks'),
  ('breakstep', 'breakstep'),
  ('brega', 'brega'),
  ('brega calypso', 'bregacalypso'),
  ('brega funk', 'bregafunk'),
  ('briddim', 'briddim'),
  ('brill building', 'brillbuilding'),
  ('brit funk', 'britfunk'),
  ('britcore', 'britcore'),
  ('british blues', 'britishblues'),
  ('british brass band', 'britishbrassband'),
  ('british folk rock', 'britishfolkrock'),
  ('british rhythm & blues', 'britishrhythmandblues'),
  ('britpop', 'britpop'),
  ('bro-country', 'brocountry'),
  ('broadband noise', 'broadbandnoise'),
  ('broken beat', 'brokenbeat'),
  ('broken transmission', 'brokentransmission'),
  ('brostep', 'brostep'),
  ('brutal death metal', 'brutaldeathmetal'),
  ('brutal prog', 'brutalprog'),
  ('bubblegum bass', 'bubblegumbass'),
  ('bubblegum dance', 'bubblegumdance'),
  ('bubblegum pop', 'bubblegumpop'),
  ('bubbling', 'bubbling'),
  ('bubbling house', 'bubblinghouse'),
  ('buchiage trance', 'buchiagetrance'),
  ('budget rock', 'budgetrock'),
  ('budots', 'budots'),
  ('bulería', 'buleria'),
  ('bullerengue', 'bullerengue'),
  ('burger-highlife', 'burgerhighlife'),
  ('burmese classical', 'burmeseclassical'),
  ('burmese mono', 'burmesemono'),
  ('burmese stereo', 'burmesestereo'),
  ('burning spirits', 'burningspirits'),
  ('burrakatha', 'burrakatha'),
  ('bytebeat', 'bytebeat'),
  ('byzantine chant', 'byzantinechant'),
  ('c-pop', 'cpop'),
  ('c86', 'c86'),
  ('ca trù', 'catru'),
  ('cabaret', 'cabaret'),
  ('cabo zouk', 'cabozouk'),
  ('cachaca', 'cachaca'),
  ('cadence lypso', 'cadencelypso'),
  ('cadence rampa', 'cadencerampa'),
  ('cải lương', 'cailuong'),
  ('cajun', 'cajun'),
  ('cakewalk', 'cakewalk'),
  ('čalgija', 'calgija'),
  ('calipso venezolano', 'calipsovenezolano'),
  ('calypso', 'calypso'),
  ('campursari', 'campursari'),
  ('campus folk', 'campusfolk'),
  ('canción melódica', 'cancionmelodica'),
  ('candombe', 'candombe'),
  ('candombe beat', 'candombebeat'),
  ('cantata', 'cantata'),
  ('cante alentejano', 'cantealentejano'),
  ('canterbury scene', 'canterburyscene'),
  ('canto a lo poeta', 'cantoalopoeta'),
  ('canto cardenche', 'cantocardenche'),
  ('canto degli alpini', 'cantodeglialpini'),
  ('cantonese opera', 'cantoneseopera'),
  ('cantopop', 'cantopop'),
  ('cantoria', 'cantoria'),
  ('cantu a chiterra', 'cantuachiterra'),
  ('cantu a tenore', 'cantuatenore'),
  ('canzona', 'canzona'),
  ('canzone d''autore', 'canzonedautore'),
  ('canzone napoletana', 'canzonenapoletana'),
  ('canzone neomelodica', 'canzoneneomelodica'),
  ('cape breton fiddling', 'capebretonfiddling'),
  ('cape jazz', 'capejazz'),
  ('caporal', 'caporal'),
  ('capriccio', 'capriccio'),
  ('carimbó', 'carimbo'),
  ('carnatic classical', 'carnaticclassical'),
  ('carnavalito', 'carnavalito'),
  ('carranga', 'carranga'),
  ('celtic', 'celtic'),
  ('celtic chant', 'celticchant'),
  ('celtic electronica', 'celticelectronica'),
  ('celtic metal', 'celticmetal'),
  ('celtic new age', 'celticnewage'),
  ('celtic punk', 'celticpunk'),
  ('celtic rock', 'celticrock'),
  ('central asian throat singing', 'centralasianthroatsinging'),
  ('chacarera', 'chacarera'),
  ('chachachá', 'chachacha'),
  ('chakacha', 'chakacha'),
  ('chalga', 'chalga'),
  ('chamamé', 'chamame'),
  ('chamamé tropical', 'chamametropical'),
  ('chamarrita açoriana', 'chamarritaacoriana'),
  ('chamarrita rioplatense', 'chamarritarioplatense'),
  ('chamber folk', 'chamberfolk'),
  ('chamber pop', 'chamberpop'),
  ('champeta', 'champeta'),
  ('changa tuki', 'changatuki'),
  ('change ringing', 'changeringing'),
  ('changjak gugak', 'changjakgugak'),
  ('changüí', 'changui'),
  ('chanson à texte', 'chansonatexte'),
  ('chanson française', 'chansonfrancaise'),
  ('chanson québécoise', 'chansonquebecoise'),
  ('chanson réaliste', 'chansonrealiste'),
  ('chaozhou xianshi', 'chaozhouxianshi'),
  ('chap hop', 'chaphop'),
  ('character piece', 'characterpiece'),
  ('charanga', 'charanga'),
  ('chazzanut', 'chazzanut'),
  ('chèo', 'cheo'),
  ('chicago blues', 'chicagoblues'),
  ('chicago bop', 'chicagobop'),
  ('chicago drill', 'chicagodrill'),
  ('chicago house', 'chicagohouse'),
  ('chicago polka', 'chicagopolka'),
  ('chicago soul', 'chicagosoul'),
  ('chicano rap', 'chicanorap'),
  ('chicha', 'chicha'),
  ('children''s music', 'childrensmusic'),
  ('chilena', 'chilena'),
  ('chillout', 'chillout'),
  ('chillstep', 'chillstep'),
  ('chillsynth', 'chillsynth'),
  ('chillwave', 'chillwave'),
  ('chimayche', 'chimayche'),
  ('chimurenga', 'chimurenga'),
  ('chinese classical', 'chineseclassical'),
  ('chinese literati music', 'chineseliteratimusic'),
  ('chinese opera', 'chineseopera'),
  ('chinese revolutionary opera', 'chineserevolutionaryopera'),
  ('chipmunk soul', 'chipmunksoul'),
  ('chiptune', 'chiptune'),
  ('chöd', 'chod'),
  ('chopped and screwed', 'choppedandscrewed'),
  ('chopper', 'chopper'),
  ('choral symphony', 'choralsymphony'),
  ('choro', 'choro'),
  ('chotis madrileño', 'chotismadrileno'),
  ('christian hardcore', 'christianhardcore'),
  ('christian hip hop', 'christianhiphop'),
  ('christian metal', 'christianmetal'),
  ('christian rock', 'christianrock'),
  ('christmas music', 'christmasmusic'),
  ('church music', 'churchmusic'),
  ('chuscada', 'chuscada'),
  ('chutney', 'chutney'),
  ('chutney soca', 'chutneysoca'),
  ('cilokaq', 'cilokaq'),
  ('cinematic classical', 'cinematicclassical'),
  ('ciranda', 'ciranda'),
  ('circus march', 'circusmarch'),
  ('city pop', 'citypop'),
  ('classic blues', 'classicblues'),
  ('classic country', 'classiccountry'),
  ('classic jazz', 'classicjazz'),
  ('classic ragtime', 'classicragtime'),
  ('classic rock', 'classicrock'),
  ('classical', 'classical'),
  ('classical crossover', 'classicalcrossover'),
  ('classical period', 'classicalperiod'),
  ('close harmony', 'closeharmony'),
  ('cloud rap', 'cloudrap'),
  ('club', 'club'),
  ('cocktail nation', 'cocktailnation'),
  ('coco', 'coco'),
  ('coke rap', 'cokerap'),
  ('coladeira', 'coladeira'),
  ('coldwave', 'coldwave'),
  ('colindă', 'colinda'),
  ('colour bass', 'colourbass'),
  ('comédie-ballet', 'comedieballet'),
  ('comedy', 'comedy'),
  ('comedy hip hop', 'comedyhiphop'),
  ('comedy rock', 'comedyrock'),
  ('comfy synth', 'comfysynth'),
  ('compas', 'compas'),
  ('complextro', 'complextro'),
  ('concert band', 'concertband'),
  ('concert spiritual', 'concertspiritual'),
  ('concertina band', 'concertinaband'),
  ('concerto', 'concerto'),
  ('concerto for orchestra', 'concertofororchestra'),
  ('concerto grosso', 'concertogrosso'),
  ('conducted improvisation', 'conductedimprovisation'),
  ('conga', 'conga'),
  ('congolese rumba', 'congoleserumba'),
  ('conscious hip hop', 'conscioushiphop'),
  ('contemporary christian', 'contemporarychristian'),
  ('contemporary classical', 'contemporaryclassical'),
  ('contemporary country', 'contemporarycountry'),
  ('contemporary folk', 'contemporaryfolk'),
  ('contemporary gospel', 'contemporarygospel'),
  ('contemporary jazz', 'contemporaryjazz'),
  ('contemporary r&b', 'contemporaryrandb'),
  ('contenance angloise', 'contenanceangloise'),
  ('contra', 'contra'),
  ('cool jazz', 'cooljazz'),
  ('coon song', 'coonsong'),
  ('copla', 'copla'),
  ('copla cajamarquina', 'coplacajamarquina'),
  ('corrido', 'corrido'),
  ('corrido tumbado', 'corridotumbado'),
  ('cosmic country', 'cosmiccountry'),
  ('country', 'country'),
  ('country and irish', 'countryandirish'),
  ('country blues', 'countryblues'),
  ('country boogie', 'countryboogie'),
  ('country folk', 'countryfolk'),
  ('country gospel', 'countrygospel'),
  ('country pop', 'countrypop'),
  ('country rap', 'countryrap'),
  ('country rock', 'countryrock'),
  ('country soul', 'countrysoul'),
  ('country yodeling', 'countryyodeling'),
  ('countrypolitan', 'countrypolitan'),
  ('coupé-décalé', 'coupedecale'),
  ('cowboy poetry', 'cowboypoetry'),
  ('cowpunk', 'cowpunk'),
  ('crack rock steady', 'crackrocksteady'),
  ('crime jazz', 'crimejazz'),
  ('crossbreed', 'crossbreed'),
  ('crossover jazz', 'crossoverjazz'),
  ('crossover prog', 'crossoverprog'),
  ('crossover thrash', 'crossoverthrash'),
  ('cruise', 'cruise'),
  ('crunk', 'crunk'),
  ('crunkcore', 'crunkcore'),
  ('crust punk', 'crustpunk'),
  ('csárdás', 'csardas'),
  ('cuarteto', 'cuarteto'),
  ('cubatón', 'cubaton'),
  ('cuddlecore', 'cuddlecore'),
  ('cueca', 'cueca'),
  ('cueca brava', 'cuecabrava'),
  ('cumbia', 'cumbia'),
  ('cumbia amazónica', 'cumbiaamazonica'),
  ('cumbia argentina', 'cumbiaargentina'),
  ('cumbia chilena', 'cumbiachilena'),
  ('cumbia colombiana', 'cumbiacolombiana'),
  ('cumbia mexicana', 'cumbiamexicana'),
  ('cumbia norteña mexicana', 'cumbianortenamexicana'),
  ('cumbia norteña peruana', 'cumbianortenaperuana'),
  ('cumbia peruana', 'cumbiaperuana'),
  ('cumbia pop', 'cumbiapop'),
  ('cumbia rebajada', 'cumbiarebajada'),
  ('cumbia salvadoreña', 'cumbiasalvadorena'),
  ('cumbia sanjuanera', 'cumbiasanjuanera'),
  ('cumbia santafesina', 'cumbiasantafesina'),
  ('cumbia sonidera', 'cumbiasonidera'),
  ('cumbia sureña peruana', 'cumbiasurenaperuana'),
  ('cumbia turra', 'cumbiaturra'),
  ('cumbia villera', 'cumbiavillera'),
  ('cumbiatón', 'cumbiaton'),
  ('cuplé', 'cuple'),
  ('currulao', 'currulao'),
  ('cururu', 'cururu'),
  ('cut-up noise', 'cutupnoise'),
  ('cyber metal', 'cybermetal'),
  ('cybergrind', 'cybergrind'),
  ('cyberpunk', 'cyberpunk'),
  ('d-beat', 'dbeat'),
  ('dabke', 'dabke'),
  ('dance', 'dance'),
  ('dance-pop', 'dancepop'),
  ('dance-punk', 'dancepunk'),
  ('dance-punk revival', 'dancepunkrevival'),
  ('dance-rock', 'dancerock'),
  ('dancefloor drum and bass', 'dancefloordrumandbass'),
  ('dancehall', 'dancehall'),
  ('dangak', 'dangak'),
  ('dangdut', 'dangdut'),
  ('danmono', 'danmono'),
  ('dansband', 'dansband'),
  ('dansktop', 'dansktop'),
  ('danzón', 'danzon'),
  ('dariacore', 'dariacore'),
  ('dark ambient', 'darkambient'),
  ('dark cabaret', 'darkcabaret'),
  ('dark disco', 'darkdisco'),
  ('dark electro', 'darkelectro'),
  ('dark folk', 'darkfolk'),
  ('dark garage', 'darkgarage'),
  ('dark jazz', 'darkjazz'),
  ('dark plugg', 'darkplugg'),
  ('dark psytrance', 'darkpsytrance'),
  ('dark wave', 'darkwave'),
  ('darkcore', 'darkcore'),
  ('darkcore edm', 'darkcoreedm'),
  ('darkstep', 'darkstep'),
  ('darksynth', 'darksynth'),
  ('data sonification', 'datasonification'),
  ('death ''n'' roll', 'deathnroll'),
  ('death industrial', 'deathindustrial'),
  ('death metal', 'deathmetal'),
  ('death-doom metal', 'deathdoommetal'),
  ('deathchant hardcore', 'deathchanthardcore'),
  ('deathcore', 'deathcore'),
  ('deathgrind', 'deathgrind'),
  ('deathrock', 'deathrock'),
  ('deathstep', 'deathstep'),
  ('dechovka', 'dechovka'),
  ('deconstructed club', 'deconstructedclub'),
  ('deejay', 'deejay'),
  ('deep drum and bass', 'deepdrumandbass'),
  ('deep funk', 'deepfunk'),
  ('deep house', 'deephouse'),
  ('deep soul', 'deepsoul'),
  ('deep tech', 'deeptech'),
  ('deep techno', 'deeptechno'),
  ('delta blues', 'deltablues'),
  ('dembow', 'dembow'),
  ('demostyle', 'demostyle'),
  ('dennery segment', 'dennerysegment'),
  ('denpa', 'denpa'),
  ('depressive black metal', 'depressiveblackmetal'),
  ('descarga', 'descarga'),
  ('desert blues', 'desertblues'),
  ('desert rock', 'desertrock'),
  ('desgarrada', 'desgarrada'),
  ('detroit techno', 'detroittechno'),
  ('detroit trap', 'detroittrap'),
  ('dhaanto', 'dhaanto'),
  ('dhol tasha', 'dholtasha'),
  ('dhrupad', 'dhrupad'),
  ('digicore', 'digicore'),
  ('digital cumbia', 'digitalcumbia'),
  ('digital fusion', 'digitalfusion'),
  ('digital hardcore', 'digitalhardcore'),
  ('dikir barat', 'dikirbarat'),
  ('dimotiko', 'dimotiko'),
  ('dirty south', 'dirtysouth'),
  ('disco', 'disco'),
  ('disco polo', 'discopolo'),
  ('dissonant black metal', 'dissonantblackmetal'),
  ('dissonant death metal', 'dissonantdeathmetal'),
  ('diva house', 'divahouse'),
  ('divertissement', 'divertissement'),
  ('dixieland', 'dixieland'),
  ('djanba', 'djanba'),
  ('djent', 'djent'),
  ('doble paso', 'doblepaso'),
  ('dobrado', 'dobrado'),
  ('dohori', 'dohori'),
  ('doina', 'doina'),
  ('dondang sayang', 'dondangsayang'),
  ('dongjing', 'dongjing'),
  ('dongzu dage', 'dongzudage'),
  ('donk', 'donk'),
  ('donosti sound', 'donostisound'),
  ('doo-wop', 'doowop'),
  ('doom metal', 'doommetal'),
  ('doomcore', 'doomcore'),
  ('doomgaze', 'doomgaze'),
  ('doskpop', 'doskpop'),
  ('downtempo', 'downtempo'),
  ('downtempo deathcore', 'downtempodeathcore'),
  ('dream pop', 'dreampop'),
  ('dream trance', 'dreamtrance'),
  ('dreampunk', 'dreampunk'),
  ('dreamwave', 'dreamwave'),
  ('drift phonk', 'driftphonk'),
  ('drill', 'drill'),
  ('drill and bass', 'drillandbass'),
  ('drinking song', 'drinkingsong'),
  ('drone', 'drone'),
  ('drone metal', 'dronemetal'),
  ('drum and bass', 'drumandbass'),
  ('drum and bugle corps', 'drumandbuglecorps'),
  ('drumfunk', 'drumfunk'),
  ('drumless hip hop', 'drumlesshiphop'),
  ('drumline', 'drumline'),
  ('drumstep', 'drumstep'),
  ('dub', 'dub'),
  ('dub poetry', 'dubpoetry'),
  ('dub techno', 'dubtechno'),
  ('dubstep', 'dubstep'),
  ('dubstyle', 'dubstyle'),
  ('dubwise', 'dubwise'),
  ('duma', 'duma'),
  ('dunedin sound', 'dunedinsound'),
  ('dungeon chip', 'dungeonchip'),
  ('dungeon rap', 'dungeonrap'),
  ('dungeon sound', 'dungeonsound'),
  ('dungeon synth', 'dungeonsynth'),
  ('duranguense', 'duranguense'),
  ('dutch house', 'dutchhouse'),
  ('dutch trancecore', 'dutchtrancecore'),
  ('eai', 'eai'),
  ('early hardstyle', 'earlyhardstyle'),
  ('east coast hip hop', 'eastcoasthiphop'),
  ('eastern-style polka', 'easternstylepolka'),
  ('easy listening', 'easylistening'),
  ('easycore', 'easycore'),
  ('ebm', 'ebm'),
  ('eccojams', 'eccojams'),
  ('edm', 'edm'),
  ('electric blues', 'electricblues'),
  ('electric texas blues', 'electrictexasblues'),
  ('electro', 'electro'),
  ('electro hop', 'electrohop'),
  ('electro house', 'electrohouse'),
  ('electro latino', 'electrolatino'),
  ('electro swing', 'electroswing'),
  ('electro trance', 'electrotrance'),
  ('electro-disco', 'electrodisco'),
  ('electro-funk', 'electrofunk'),
  ('electro-industrial', 'electroindustrial'),
  ('electroacoustic', 'electroacoustic'),
  ('electroclash', 'electroclash'),
  ('electronic', 'electronic'),
  ('electronic rock', 'electronicrock'),
  ('electronica', 'electronica'),
  ('electronicore', 'electronicore'),
  ('electropop', 'electropop'),
  ('electropunk', 'electropunk'),
  ('electrotango', 'electrotango'),
  ('eleki', 'eleki'),
  ('eletrofunk', 'eletrofunk'),
  ('embolada', 'embolada'),
  ('emo', 'emo'),
  ('emo pop', 'emopop'),
  ('emo rap', 'emorap'),
  ('emocore', 'emocore'),
  ('emoviolence', 'emoviolence'),
  ('english pastoral school', 'englishpastoralschool'),
  ('enka', 'enka'),
  ('éntekhno', 'entekhno'),
  ('epic collage', 'epiccollage'),
  ('epic doom metal', 'epicdoommetal'),
  ('epic house', 'epichouse'),
  ('estrada', 'estrada'),
  ('ethereal wave', 'etherealwave'),
  ('ethio-jazz', 'ethiojazz'),
  ('étude', 'etude'),
  ('euphoric hardstyle', 'euphorichardstyle'),
  ('euro house', 'eurohouse'),
  ('euro-disco', 'eurodisco'),
  ('euro-trance', 'eurotrance'),
  ('eurobeat', 'eurobeat'),
  ('eurodance', 'eurodance'),
  ('europop', 'europop'),
  ('euskal kantagintza berria', 'euskalkantagintzaberria'),
  ('exotica', 'exotica'),
  ('experimental', 'experimental'),
  ('experimental big band', 'experimentalbigband'),
  ('experimental electronic', 'experimentalelectronic'),
  ('experimental hip hop', 'experimentalhiphop'),
  ('experimental rock', 'experimentalrock'),
  ('expressionism', 'expressionism'),
  ('extratone', 'extratone'),
  ('fado', 'fado'),
  ('fado de coimbra', 'fadodecoimbra'),
  ('fahrtenlied', 'fahrtenlied'),
  ('fairy tale', 'fairytale'),
  ('fakaseasea', 'fakaseasea'),
  ('falak', 'falak'),
  ('famo', 'famo'),
  ('fandango', 'fandango'),
  ('fandango caiçara', 'fandangocaicara'),
  ('fantasia', 'fantasia'),
  ('fantezi', 'fantezi'),
  ('festejo', 'festejo'),
  ('festival progressive house', 'festivalprogressivehouse'),
  ('festival trap', 'festivaltrap'),
  ('fidget house', 'fidgethouse'),
  ('field recording', 'fieldrecording'),
  ('fife and drum', 'fifeanddrum'),
  ('fife and drum blues', 'fifeanddrumblues'),
  ('fijiri', 'fijiri'),
  ('filin', 'filin'),
  ('filipino rondalla', 'filipinorondalla'),
  ('filk', 'filk'),
  ('filmi', 'filmi'),
  ('finnish tango', 'finnishtango'),
  ('flamenco', 'flamenco'),
  ('flamenco jazz', 'flamencojazz'),
  ('flamenco pop', 'flamencopop'),
  ('flashcore', 'flashcore'),
  ('flex dance music', 'flexdancemusic'),
  ('florida breaks', 'floridabreaks'),
  ('fm synthesis', 'fmsynthesis'),
  ('folk', 'folk'),
  ('folk metal', 'folkmetal'),
  ('folk pop', 'folkpop'),
  ('folk punk', 'folkpunk'),
  ('folk rock', 'folkrock'),
  ('folkhop', 'folkhop'),
  ('folktronica', 'folktronica'),
  ('fon leb', 'fonleb'),
  ('football chant', 'footballchant'),
  ('footwork', 'footwork'),
  ('footwork jungle', 'footworkjungle'),
  ('forest psytrance', 'forestpsytrance'),
  ('forró', 'forro'),
  ('forró de favela', 'forrodefavela'),
  ('forró eletrônico', 'forroeletronico'),
  ('forró universitário', 'forrouniversitario'),
  ('frapcore', 'frapcore'),
  ('frat rap', 'fratrap'),
  ('frat rock', 'fratrock'),
  ('freak folk', 'freakfolk'),
  ('freakbeat', 'freakbeat'),
  ('free car music', 'freecarmusic'),
  ('free folk', 'freefolk'),
  ('free funk', 'freefunk'),
  ('free improvisation', 'freeimprovisation'),
  ('free jazz', 'freejazz'),
  ('free tekno', 'freetekno'),
  ('freeform hardcore', 'freeformhardcore'),
  ('freestyle', 'freestyle'),
  ('french electro', 'frenchelectro'),
  ('french house', 'frenchhouse'),
  ('frenchcore', 'frenchcore'),
  ('frenchtek', 'frenchtek'),
  ('frevo', 'frevo'),
  ('frevo de bloco', 'frevodebloco'),
  ('frevo de rua', 'frevoderua'),
  ('frevo elétrico', 'frevoeletrico'),
  ('frevo-canção', 'frevocancao'),
  ('fugue', 'fugue'),
  ('fuji', 'fuji'),
  ('full-on', 'fullon'),
  ('funaná', 'funana'),
  ('funeral doom metal', 'funeraldoommetal'),
  ('funeral march', 'funeralmarch'),
  ('fungi', 'fungi'),
  ('funk', 'funk'),
  ('funk automotivo', 'funkautomotivo'),
  ('funk brasileiro', 'funkbrasileiro'),
  ('funk carioca', 'funkcarioca'),
  ('funk consciente', 'funkconsciente'),
  ('funk de bh', 'funkdebh'),
  ('funk mandelão', 'funkmandelao'),
  ('funk melody', 'funkmelody'),
  ('funk metal', 'funkmetal'),
  ('funk ostentação', 'funkostentacao'),
  ('funk proibidão', 'funkproibidao'),
  ('funk rock', 'funkrock'),
  ('funknejo', 'funknejo'),
  ('funkot', 'funkot'),
  ('funktronica', 'funktronica'),
  ('funky breaks', 'funkybreaks'),
  ('funky house', 'funkyhouse'),
  ('fusion gugak', 'fusiongugak'),
  ('future bass', 'futurebass'),
  ('future bounce', 'futurebounce'),
  ('future core', 'futurecore'),
  ('future funk', 'futurefunk'),
  ('future garage', 'futuregarage'),
  ('future house', 'futurehouse'),
  ('future rave', 'futurerave'),
  ('future riddim', 'futureriddim'),
  ('futurepop', 'futurepop'),
  ('futurism', 'futurism'),
  ('g-funk', 'gfunk'),
  ('g-house', 'ghouse'),
  ('gaana', 'gaana'),
  ('gabber', 'gabber'),
  ('gaelic psalm singing', 'gaelicpsalmsinging'),
  ('gagaku', 'gagaku'),
  ('gagok', 'gagok'),
  ('gaita zuliana', 'gaitazuliana'),
  ('gallican chant', 'gallicanchant'),
  ('gambang kromong', 'gambangkromong'),
  ('gamelan', 'gamelan'),
  ('gamelan angklung', 'gamelanangklung'),
  ('gamelan beleganjur', 'gamelanbeleganjur'),
  ('gamelan degung', 'gamelandegung'),
  ('gamelan gambang', 'gamelangambang'),
  ('gamelan gender wayang', 'gamelangenderwayang'),
  ('gamelan gong gede', 'gamelangonggede'),
  ('gamelan gong kebyar', 'gamelangongkebyar'),
  ('gamelan jegog', 'gamelanjegog'),
  ('gamelan joged bumbung', 'gamelanjogedbumbung'),
  ('gamelan salendro', 'gamelansalendro'),
  ('gamelan sekaten', 'gamelansekaten'),
  ('gamelan selunding', 'gamelanselunding'),
  ('gamelan semar pegulingan', 'gamelansemarpegulingan'),
  ('gamelan siteran', 'gamelansiteran'),
  ('gamelan surakarta', 'gamelansurakarta'),
  ('gangsta rap', 'gangstarap'),
  ('garage house', 'garagehouse'),
  ('garage psych', 'garagepsych'),
  ('garage punk', 'garagepunk'),
  ('garage rock', 'garagerock'),
  ('garage rock revival', 'garagerockrevival'),
  ('garba', 'garba'),
  ('geek rock', 'geekrock'),
  ('género chico', 'generochico'),
  ('género grande', 'generogrande'),
  ('genge', 'genge'),
  ('gengetone', 'gengetone'),
  ('għana', 'għana'),
  ('ghazal', 'ghazal'),
  ('ghetto funk', 'ghettofunk'),
  ('ghetto house', 'ghettohouse'),
  ('ghettotech', 'ghettotech'),
  ('ginan', 'ginan'),
  ('glam', 'glam'),
  ('glam metal', 'glammetal'),
  ('glam punk', 'glampunk'),
  ('glam rock', 'glamrock'),
  ('glitch', 'glitch'),
  ('glitch hop', 'glitchhop'),
  ('glitch hop edm', 'glitchhopedm'),
  ('glitch pop', 'glitchpop'),
  ('gnawa', 'gnawa'),
  ('go-go', 'gogo'),
  ('goa trance', 'goatrance'),
  ('gommance', 'gommance'),
  ('gondang', 'gondang'),
  ('goombay', 'goombay'),
  ('goregrind', 'goregrind'),
  ('gorenoise', 'gorenoise'),
  ('gospel', 'gospel'),
  ('gospel house', 'gospelhouse'),
  ('gospel hymn', 'gospelhymn'),
  ('gospel reggae', 'gospelreggae'),
  ('gothic', 'gothic'),
  ('gothic country', 'gothiccountry'),
  ('gothic metal', 'gothicmetal'),
  ('gothic rock', 'gothicrock'),
  ('gqom', 'gqom'),
  ('grand opera', 'grandopera'),
  ('graphical sound', 'graphicalsound'),
  ('grebo', 'grebo'),
  ('gregorian chant', 'gregorianchant'),
  ('grime', 'grime'),
  ('grindcore', 'grindcore'),
  ('griot', 'griot'),
  ('groove metal', 'groovemetal'),
  ('group sounds', 'groupsounds'),
  ('grunge', 'grunge'),
  ('grupera', 'grupera'),
  ('gstanzl', 'gstanzl'),
  ('guaguancó', 'guaguanco'),
  ('guajira', 'guajira'),
  ('guangdong yinyue', 'guangdongyinyue'),
  ('guaracha', 'guaracha'),
  ('guaracha edm', 'guarachaedm'),
  ('guaracha santiagueña', 'guarachasantiaguena'),
  ('guarania', 'guarania'),
  ('guayla', 'guayla'),
  ('gufeng', 'gufeng'),
  ('guggenmusik', 'guggenmusik'),
  ('guided meditation', 'guidedmeditation'),
  ('guitarrada', 'guitarrada'),
  ('gumbe', 'gumbe'),
  ('guoyue', 'guoyue'),
  ('gwo ka', 'gwoka'),
  ('gypsy jazz', 'gypsyjazz'),
  ('gypsy punk', 'gypsypunk'),
  ('habanera', 'habanera'),
  ('haitian vodou drumming', 'haitianvodoudrumming'),
  ('halftime', 'halftime'),
  ('hambo', 'hambo'),
  ('hamburger schule', 'hamburgerschule'),
  ('hands up', 'handsup'),
  ('hanmai', 'hanmai'),
  ('haozi', 'haozi'),
  ('hapa haole', 'hapahaole'),
  ('happy hardcore', 'happyhardcore'),
  ('harana', 'harana'),
  ('harawi', 'harawi'),
  ('hard beat', 'hardbeat'),
  ('hard bop', 'hardbop'),
  ('hard drum', 'harddrum'),
  ('hard house', 'hardhouse'),
  ('hard nrg', 'hardnrg'),
  ('hard renaissance', 'hardrenaissance'),
  ('hard rock', 'hardrock'),
  ('hard techno', 'hardtechno'),
  ('hard trance', 'hardtrance'),
  ('hard trap', 'hardtrap'),
  ('hardbag', 'hardbag'),
  ('hardbass', 'hardbass'),
  ('hardcore breaks', 'hardcorebreaks'),
  ('hardcore hip hop', 'hardcorehiphop'),
  ('hardcore punk', 'hardcorepunk'),
  ('hardcore techno', 'hardcoretechno'),
  ('hardgroove techno', 'hardgroovetechno'),
  ('hardstep', 'hardstep'),
  ('hardstyle', 'hardstyle'),
  ('hardtekk', 'hardtekk'),
  ('hardvapour', 'hardvapour'),
  ('hardwave', 'hardwave'),
  ('harsh noise', 'harshnoise'),
  ('harsh noise wall', 'harshnoisewall'),
  ('hát tuồng', 'hattuong'),
  ('hauntology', 'hauntology'),
  ('heartland rock', 'heartlandrock'),
  ('heaven trap', 'heaventrap'),
  ('heavy metal', 'heavymetal'),
  ('heavy psych', 'heavypsych'),
  ('heikyoku', 'heikyoku'),
  ('henan opera', 'henanopera'),
  ('hexd', 'hexd'),
  ('hi-nrg', 'hinrg'),
  ('hi-tech', 'hitech'),
  ('hi-tech full-on', 'hitechfullon'),
  ('highlife', 'highlife'),
  ('hill country blues', 'hillcountryblues'),
  ('himene tarava', 'himenetarava'),
  ('hindustani classical', 'hindustaniclassical'),
  ('hip hop', 'hiphop'),
  ('hip hop soul', 'hiphopsoul'),
  ('hip house', 'hiphouse'),
  ('hipco', 'hipco'),
  ('hiplife', 'hiplife'),
  ('holy minimalism', 'holyminimalism'),
  ('honky tonk', 'honkytonk'),
  ('honkyoku', 'honkyoku'),
  ('hopepunk', 'hopepunk'),
  ('hornpipe', 'hornpipe'),
  ('horror punk', 'horrorpunk'),
  ('horror synth', 'horrorsynth'),
  ('horrorcore', 'horrorcore'),
  ('hot rod music', 'hotrodmusic'),
  ('house', 'house'),
  ('houston sound', 'houstonsound'),
  ('huapango', 'huapango'),
  ('huaylarsh', 'huaylarsh'),
  ('huayno', 'huayno'),
  ('huayno con arpa', 'huaynoconarpa'),
  ('humppa', 'humppa'),
  ('hungarian folk', 'hungarianfolk'),
  ('hyangak', 'hyangak'),
  ('hybrid trap', 'hybridtrap'),
  ('hyper techno', 'hypertechno'),
  ('hyperpop', 'hyperpop'),
  ('hyphy', 'hyphy'),
  ('hypnagogic pop', 'hypnagogicpop'),
  ('ʻōteʻa', 'ʻoteʻa'),
  ('iavnana', 'iavnana'),
  ('idm', 'idm'),
  ('idol kayō', 'idolkayo'),
  ('illbient', 'illbient'),
  ('impressionism', 'impressionism'),
  ('impromptu', 'impromptu'),
  ('indeterminacy', 'indeterminacy'),
  ('indian classical', 'indianclassical'),
  ('indian pop', 'indianpop'),
  ('indie folk', 'indiefolk'),
  ('indie pop', 'indiepop'),
  ('indie rock', 'indierock'),
  ('indie surf', 'indiesurf'),
  ('indietronica', 'indietronica'),
  ('indo jazz', 'indojazz'),
  ('indorock', 'indorock'),
  ('industrial', 'industrial'),
  ('industrial folk song', 'industrialfolksong'),
  ('industrial hardcore', 'industrialhardcore'),
  ('industrial hip hop', 'industrialhiphop'),
  ('industrial metal', 'industrialmetal'),
  ('industrial musical', 'industrialmusical'),
  ('industrial rock', 'industrialrock'),
  ('industrial techno', 'industrialtechno'),
  ('instrumental', 'instrumental'),
  ('instrumental hip hop', 'instrumentalhiphop'),
  ('instrumental jazz', 'instrumentaljazz'),
  ('instrumental rock', 'instrumentalrock'),
  ('integral serialism', 'integralserialism'),
  ('interview', 'interview'),
  ('iraqi maqam', 'iraqimaqam'),
  ('irish folk', 'irishfolk'),
  ('isa', 'isa'),
  ('isicathamiya', 'isicathamiya'),
  ('islamic modal music', 'islamicmodalmusic'),
  ('italo dance', 'italodance'),
  ('italo house', 'italohouse'),
  ('italo-disco', 'italodisco'),
  ('izlan', 'izlan'),
  ('izvorna bosanska muzika', 'izvornabosanskamuzika'),
  ('j-core', 'jcore'),
  ('j-euro', 'jeuro'),
  ('j-pop', 'jpop'),
  ('j-rock', 'jrock'),
  ('jácara', 'jacara'),
  ('jackin house', 'jackinhouse'),
  ('jaipongan', 'jaipongan'),
  ('jam band', 'jamband'),
  ('jamaican ska', 'jamaicanska'),
  ('james bay fiddling', 'jamesbayfiddling'),
  ('jamgrass', 'jamgrass'),
  ('jangle pop', 'janglepop'),
  ('japanese classical', 'japaneseclassical'),
  ('javanese gamelan', 'javanesegamelan'),
  ('jawaiian', 'jawaiian'),
  ('jazz', 'jazz'),
  ('jazz blues', 'jazzblues'),
  ('jazz fusion', 'jazzfusion'),
  ('jazz guachaca', 'jazzguachaca'),
  ('jazz house', 'jazzhouse'),
  ('jazz mugham', 'jazzmugham'),
  ('jazz poetry', 'jazzpoetry'),
  ('jazz pop', 'jazzpop'),
  ('jazz rap', 'jazzrap'),
  ('jazz rock', 'jazzrock'),
  ('jazz-funk', 'jazzfunk'),
  ('jazzstep', 'jazzstep'),
  ('jeongak', 'jeongak'),
  ('jerk', 'jerk'),
  ('jerk rap', 'jerkrap'),
  ('jersey club', 'jerseyclub'),
  ('jersey club rap', 'jerseyclubrap'),
  ('jersey drill', 'jerseydrill'),
  ('jersey sound', 'jerseysound'),
  ('jesus music', 'jesusmusic'),
  ('jhumar', 'jhumar'),
  ('jiangnan sizhu', 'jiangnansizhu'),
  ('jibonmukhi gaan', 'jibonmukhigaan'),
  ('jit', 'jit'),
  ('jiuta', 'jiuta'),
  ('joik', 'joik'),
  ('jongo', 'jongo'),
  ('joropo', 'joropo'),
  ('jōruri', 'joruri'),
  ('jota', 'jota'),
  ('jovem guarda', 'jovemguarda'),
  ('jubilee', 'jubilee'),
  ('jug band', 'jugband'),
  ('jùjú', 'juju'),
  ('juke', 'juke'),
  ('jump blues', 'jumpblues'),
  ('jump up', 'jumpup'),
  ('jumpstyle', 'jumpstyle'),
  ('jungle', 'jungle'),
  ('jungle dutch', 'jungledutch'),
  ('jungle techno', 'jungletechno'),
  ('jungle terror', 'jungleterror'),
  ('junkanoo', 'junkanoo'),
  ('k-pop', 'kpop'),
  ('kabarett', 'kabarett'),
  ('kacapi suling', 'kacapisuling'),
  ('kadodi', 'kadodi'),
  ('kadongo kamu', 'kadongokamu'),
  ('kafi', 'kafi'),
  ('kagura', 'kagura'),
  ('kai', 'kai'),
  ('kakawin', 'kakawin'),
  ('kalattut', 'kalattut'),
  ('kalindula', 'kalindula'),
  ('kalon''ny fahiny', 'kalonnyfahiny'),
  ('kan ha diskan', 'kanhadiskan'),
  ('kaneka', 'kaneka'),
  ('kankyō ongaku', 'kankyoongaku'),
  ('kantan chamorrita', 'kantanchamorrita'),
  ('kanto', 'kanto'),
  ('kantruem', 'kantruem'),
  ('kapuka', 'kapuka'),
  ('kaseko', 'kaseko'),
  ('kawaii future bass', 'kawaiifuturebass'),
  ('kawaii metal', 'kawaiimetal'),
  ('kayōkyoku', 'kayokyoku'),
  ('kecak', 'kecak'),
  ('keller synth', 'kellersynth'),
  ('keroncong', 'keroncong'),
  ('kete', 'kete'),
  ('ketuk tilu', 'ketuktilu'),
  ('khrueang sai', 'khrueangsai'),
  ('khyal', 'khyal'),
  ('kidandali', 'kidandali'),
  ('kidumbak', 'kidumbak'),
  ('kilapanga', 'kilapanga'),
  ('kirtan', 'kirtan'),
  ('kizomba', 'kizomba'),
  ('klapa', 'klapa'),
  ('klasik', 'klasik'),
  ('kleinkunst', 'kleinkunst'),
  ('klezmer', 'klezmer'),
  ('kliningan', 'kliningan'),
  ('konnakol', 'konnakol'),
  ('könsrock', 'konsrock'),
  ('kontakion', 'kontakion'),
  ('koplo', 'koplo'),
  ('korean ballad', 'koreanballad'),
  ('korean classical', 'koreanclassical'),
  ('korean revolutionary opera', 'koreanrevolutionaryopera'),
  ('kouta', 'kouta'),
  ('krakowiak', 'krakowiak'),
  ('krautrock', 'krautrock'),
  ('kréyol djaz', 'kreyoldjaz'),
  ('krushclub', 'krushclub'),
  ('kuda lumping', 'kudalumping'),
  ('kuduro', 'kuduro'),
  ('kujawiak', 'kujawiak'),
  ('kulintang', 'kulintang'),
  ('kumi-daiko', 'kumidaiko'),
  ('kumiuta', 'kumiuta'),
  ('kundiman', 'kundiman'),
  ('kunqu', 'kunqu'),
  ('kwaito', 'kwaito'),
  ('kwassa kwassa', 'kwassakwassa'),
  ('kwela', 'kwela'),
  ('kyivan chant', 'kyivanchant'),
  ('laiko', 'laiko'),
  ('lambada', 'lambada'),
  ('ländlermusik', 'landlermusik'),
  ('landó', 'lando'),
  ('langgam jawa', 'langgamjawa'),
  ('latin', 'latin'),
  ('latin ballad', 'latinballad'),
  ('latin disco', 'latindisco'),
  ('latin funk', 'latinfunk'),
  ('latin house', 'latinhouse'),
  ('latin jazz', 'latinjazz'),
  ('latin pop', 'latinpop'),
  ('latin rock', 'latinrock'),
  ('latin soul', 'latinsoul'),
  ('lauda', 'lauda'),
  ('lavani', 'lavani'),
  ('lecture', 'lecture'),
  ('leftfield', 'leftfield'),
  ('lento violento', 'lentoviolento'),
  ('levenslied', 'levenslied'),
  ('lied', 'lied'),
  ('liedermacher', 'liedermacher'),
  ('liquid funk', 'liquidfunk'),
  ('liquid riddim', 'liquidriddim'),
  ('liscio', 'liscio'),
  ('livetronica', 'livetronica'),
  ('liwa', 'liwa'),
  ('lo-fi', 'lofi'),
  ('lo-fi hip hop', 'lofihiphop'),
  ('lo-fi house', 'lofihouse'),
  ('lolicore', 'lolicore'),
  ('loner folk', 'lonerfolk'),
  ('loud kei', 'loudkei'),
  ('louisiana blues', 'louisianablues'),
  ('lounge', 'lounge'),
  ('lovers rock', 'loversrock'),
  ('lowend', 'lowend'),
  ('lowercase', 'lowercase'),
  ('luk krung', 'lukkrung'),
  ('luk thung', 'lukthung'),
  ('lullaby', 'lullaby'),
  ('lundu', 'lundu'),
  ('lute song', 'lutesong'),
  ('machine rock', 'machinerock'),
  ('mad', 'mad'),
  ('madchester', 'madchester'),
  ('maddahi', 'maddahi'),
  ('madrigal', 'madrigal'),
  ('mafioso rap', 'mafiosorap'),
  ('maftirim', 'maftirim'),
  ('mahori', 'mahori'),
  ('mahraganat', 'mahraganat'),
  ('mainstream rock', 'mainstreamrock'),
  ('makina', 'makina'),
  ('makossa', 'makossa'),
  ('malagueña venezolana', 'malaguenavenezolana'),
  ('malay gamelan', 'malaygamelan'),
  ('malhun', 'malhun'),
  ('mallsoft', 'mallsoft'),
  ('malouf', 'malouf'),
  ('maloya', 'maloya'),
  ('maloya électronique', 'maloyaelectronique'),
  ('maloya élektrik', 'maloyaelektrik'),
  ('mambo', 'mambo'),
  ('mambo chileno', 'mambochileno'),
  ('mambo urbano', 'mambourbano'),
  ('mandopop', 'mandopop'),
  ('manele', 'manele'),
  ('mangambeu', 'mangambeu'),
  ('mangue beat', 'manguebeat'),
  ('manila sound', 'manilasound'),
  ('mantra', 'mantra'),
  ('manyao', 'manyao'),
  ('mappila', 'mappila'),
  ('marabi', 'marabi'),
  ('maracatu', 'maracatu'),
  ('march', 'march'),
  ('marching band', 'marchingband'),
  ('marchinha', 'marchinha'),
  ('mariachi', 'mariachi'),
  ('marinera', 'marinera'),
  ('marinera norteña', 'marineranortena'),
  ('marrabenta', 'marrabenta'),
  ('martial industrial', 'martialindustrial'),
  ('mashcore', 'mashcore'),
  ('maskanda', 'maskanda'),
  ('mass', 'mass'),
  ('mataali', 'mataali'),
  ('math pop', 'mathpop'),
  ('math rock', 'mathrock'),
  ('mathcore', 'mathcore'),
  ('maxixe', 'maxixe'),
  ('mazurka', 'mazurka'),
  ('mbalax', 'mbalax'),
  ('mbaqanga', 'mbaqanga'),
  ('mbolé', 'mbole'),
  ('mbube', 'mbube'),
  ('mchiriku', 'mchiriku'),
  ('medieval', 'medieval'),
  ('medieval lyric poetry', 'medievallyricpoetry'),
  ('medieval metal', 'medievalmetal'),
  ('medieval rock', 'medievalrock'),
  ('mega funk', 'megafunk'),
  ('meiji shinkyoku', 'meijishinkyoku'),
  ('melbourne bounce', 'melbournebounce'),
  ('melodic bass', 'melodicbass'),
  ('melodic black metal', 'melodicblackmetal'),
  ('melodic death metal', 'melodicdeathmetal'),
  ('melodic dubstep', 'melodicdubstep'),
  ('melodic hardcore', 'melodichardcore'),
  ('melodic house', 'melodichouse'),
  ('melodic metalcore', 'melodicmetalcore'),
  ('melodic techno', 'melodictechno'),
  ('melodic trance', 'melodictrance'),
  ('mélodie', 'melodie'),
  ('memphis rap', 'memphisrap'),
  ('mento', 'mento'),
  ('menzuma', 'menzuma'),
  ('merecumbé', 'merecumbe'),
  ('merengue', 'merengue'),
  ('merengue típico', 'merenguetipico'),
  ('merenhouse', 'merenhouse'),
  ('merequetengue', 'merequetengue'),
  ('méringue', 'meringue'),
  ('merseybeat', 'merseybeat'),
  ('metal', 'metal'),
  ('metalcore', 'metalcore'),
  ('métis fiddling', 'metisfiddling'),
  ('meyxana', 'meyxana'),
  ('mgodro', 'mgodro'),
  ('miami bass', 'miamibass'),
  ('microfunk', 'microfunk'),
  ('microhouse', 'microhouse'),
  ('microsound', 'microsound'),
  ('microtonal classical', 'microtonalclassical'),
  ('midtempo bass', 'midtempobass'),
  ('midwest emo', 'midwestemo'),
  ('miejski folk', 'miejskifolk'),
  ('military cadence', 'militarycadence'),
  ('milonga', 'milonga'),
  ('min''yō', 'minyo'),
  ('minatory', 'minatory'),
  ('mincecore', 'mincecore'),
  ('minimal drum and bass', 'minimaldrumandbass'),
  ('minimal synth', 'minimalsynth'),
  ('minimal techno', 'minimaltechno'),
  ('minimal wave', 'minimalwave'),
  ('minimalism', 'minimalism'),
  ('minneapolis sound', 'minneapolissound'),
  ('minnesang', 'minnesang'),
  ('minstrelsy', 'minstrelsy'),
  ('mobb music', 'mobbmusic'),
  ('mod', 'mod'),
  ('mod revival', 'modrevival'),
  ('moda de viola', 'modadeviola'),
  ('modal jazz', 'modaljazz'),
  ('modern blues', 'modernblues'),
  ('modern classical', 'modernclassical'),
  ('modern creative', 'moderncreative'),
  ('modern hardtek', 'modernhardtek'),
  ('modern laiko', 'modernlaiko'),
  ('modinha', 'modinha'),
  ('moe song', 'moesong'),
  ('monodrama', 'monodrama'),
  ('mood kayō', 'moodkayo'),
  ('moogsploitation', 'moogsploitation'),
  ('moombahcore', 'moombahcore'),
  ('moombahton', 'moombahton'),
  ('mor lam', 'morlam'),
  ('mor lam sing', 'morlamsing'),
  ('morenada', 'morenada'),
  ('morna', 'morna'),
  ('moroccan chaabi', 'moroccanchaabi'),
  ('motet', 'motet'),
  ('motown', 'motown'),
  ('moutya', 'moutya'),
  ('movimiento alterado', 'movimientoalterado'),
  ('mozarabic chant', 'mozarabicchant'),
  ('mpb', 'mpb'),
  ('muak', 'muak'),
  ('mugham', 'mugham'),
  ('mugithi', 'mugithi'),
  ('muiñeira', 'muineira'),
  ('mulatós', 'mulatos'),
  ('muliza', 'muliza'),
  ('murga', 'murga'),
  ('murga uruguaya', 'murgauruguaya'),
  ('musette', 'musette'),
  ('music hall', 'musichall'),
  ('música cebolla', 'musicacebolla'),
  ('música criolla', 'musicacriolla'),
  ('música de intervenção', 'musicadeintervencao'),
  ('música festera', 'musicafestera'),
  ('música llanera', 'musicallanera'),
  ('música típica chilena', 'musicatipicachilena'),
  ('musical', 'musical'),
  ('mūsīqā lubnāniyya', 'musiqalubnaniyya'),
  ('musique concrète', 'musiqueconcrete'),
  ('musique concrète instrumentale', 'musiqueconcreteinstrumentale'),
  ('muzika mizrahit', 'muzikamizrahit'),
  ('muzika yehudit mekorit', 'muzikayehuditmekorit'),
  ('muzikat dika''on', 'muzikatdikaon'),
  ('muziki wa dansi', 'muzikiwadansi'),
  ('nagara naam', 'nagaranaam'),
  ('nagauta', 'nagauta'),
  ('nanguan', 'nanguan'),
  ('narcocorrido', 'narcocorrido'),
  ('narodnozabavna glasba', 'narodnozabavnaglasba'),
  ('nasheed', 'nasheed'),
  ('nashville sound', 'nashvillesound'),
  ('native american new age', 'nativeamericannewage'),
  ('nature sounds', 'naturesounds'),
  ('natya sangeet', 'natyasangeet'),
  ('nederbeat', 'nederbeat'),
  ('nederpop', 'nederpop'),
  ('neo kyma', 'neokyma'),
  ('neo rave', 'neorave'),
  ('neo soul', 'neosoul'),
  ('neo-acoustic', 'neoacoustic'),
  ('neo-bop', 'neobop'),
  ('neo-city pop', 'neocitypop'),
  ('neo-grime', 'neogrime'),
  ('neo-medieval folk', 'neomedievalfolk'),
  ('neo-progressive rock', 'neoprogressiverock'),
  ('neo-psychedelia', 'neopsychedelia'),
  ('neo-rockabilly', 'neorockabilly'),
  ('néo-trad', 'neotrad'),
  ('neo-traditional country', 'neotraditionalcountry'),
  ('neoclassical dark wave', 'neoclassicaldarkwave'),
  ('neoclassical metal', 'neoclassicalmetal'),
  ('neoclassical new age', 'neoclassicalnewage'),
  ('neoclassicism', 'neoclassicism'),
  ('neocrust', 'neocrust'),
  ('neofolk', 'neofolk'),
  ('neofolklore', 'neofolklore'),
  ('neon pop punk', 'neonpoppunk'),
  ('neoperreo', 'neoperreo'),
  ('neoromanticism', 'neoromanticism'),
  ('nepali lok geet', 'nepalilokgeet'),
  ('nerdcore', 'nerdcore'),
  ('nerdcore techno', 'nerdcoretechno'),
  ('neue deutsche härte', 'neuedeutscheharte'),
  ('neue deutsche todeskunst', 'neuedeutschetodeskunst'),
  ('neue deutsche welle', 'neuedeutschewelle'),
  ('neurofunk', 'neurofunk'),
  ('neurohop', 'neurohop'),
  ('new age', 'newage'),
  ('new beat', 'newbeat'),
  ('new complexity', 'newcomplexity'),
  ('new jack swing', 'newjackswing'),
  ('new jazz', 'newjazz'),
  ('new mexico music', 'newmexicomusic'),
  ('new orleans blues', 'neworleansblues'),
  ('new orleans r&b', 'neworleansrandb'),
  ('new rave', 'newrave'),
  ('new romantic', 'newromantic'),
  ('new wave', 'newwave'),
  ('new york drill', 'newyorkdrill'),
  ('ngâm thơ', 'ngamtho'),
  ('ngoma', 'ngoma'),
  ('nhạc đỏ', 'nhacđo'),
  ('nhạc tiền chiến', 'nhactienchien'),
  ('nhạc vàng', 'nhacvang'),
  ('night full-on', 'nightfullon'),
  ('nightcore', 'nightcore'),
  ('nigun', 'nigun'),
  ('nintendocore', 'nintendocore'),
  ('nitzhonot', 'nitzhonot'),
  ('njuup', 'njuup'),
  ('no melody trap', 'nomelodytrap'),
  ('no wave', 'nowave'),
  ('nocturne', 'nocturne'),
  ('noh', 'noh'),
  ('noiadance', 'noiadance'),
  ('noise', 'noise'),
  ('noise pop', 'noisepop'),
  ('noise rock', 'noiserock'),
  ('noisecore', 'noisecore'),
  ('noisegrind', 'noisegrind'),
  ('non-music', 'nonmusic'),
  ('nortec', 'nortec'),
  ('norteño', 'norteno'),
  ('northern soul', 'northernsoul'),
  ('nóta', 'nota'),
  ('nouveau zydeco', 'nouveauzydeco'),
  ('nova cançó', 'novacanco'),
  ('novelty piano', 'noveltypiano'),
  ('novo dub', 'novodub'),
  ('nu disco', 'nudisco'),
  ('nu jazz', 'nujazz'),
  ('nu metal', 'numetal'),
  ('nu skool breaks', 'nuskoolbreaks'),
  ('nu style gabber', 'nustylegabber'),
  ('nueva canción', 'nuevacancion'),
  ('nueva canción chilena', 'nuevacancionchilena'),
  ('nueva canción española', 'nuevacancionespanola'),
  ('nueva cumbia chilena', 'nuevacumbiachilena'),
  ('nueva trova', 'nuevatrova'),
  ('nuevo cancionero', 'nuevocancionero'),
  ('nuevo flamenco', 'nuevoflamenco'),
  ('nuevo tango', 'nuevotango'),
  ('nustyle', 'nustyle'),
  ('nwobhm', 'nwobhm'),
  ('nyū myūjikku', 'nyumyujikku'),
  ('oberek', 'oberek'),
  ('occult rock', 'occultrock'),
  ('odissi classical', 'odissiclassical'),
  ('ogene music', 'ogenemusic'),
  ('oi', 'oi'),
  ('old roman chant', 'oldromanchant'),
  ('old school death metal', 'oldschooldeathmetal'),
  ('old school hip hop', 'oldschoolhiphop'),
  ('old-time', 'oldtime'),
  ('omutibo', 'omutibo'),
  ('onda nueva', 'ondanueva'),
  ('ondō', 'ondo'),
  ('onkyo', 'onkyo'),
  ('opera', 'opera'),
  ('opera buffa', 'operabuffa'),
  ('opéra comique', 'operacomique'),
  ('opera semiseria', 'operasemiseria'),
  ('opera seria', 'operaseria'),
  ('opera-ballet', 'operaballet'),
  ('operatic pop', 'operaticpop'),
  ('operetta', 'operetta'),
  ('opm', 'opm'),
  ('oratorio', 'oratorio'),
  ('orchestral', 'orchestral'),
  ('orchestral jazz', 'orchestraljazz'),
  ('orchestral song', 'orchestralsong'),
  ('organic house', 'organichouse'),
  ('ori deck', 'orideck'),
  ('oriental ballad', 'orientalballad'),
  ('orkes gambus', 'orkesgambus'),
  ('orthodox pop', 'orthodoxpop'),
  ('outlaw country', 'outlawcountry'),
  ('outrun', 'outrun'),
  ('outsider house', 'outsiderhouse'),
  ('overture', 'overture'),
  ('özgün müzik', 'ozgunmuzik'),
  ('p-funk', 'pfunk'),
  ('pachanga', 'pachanga'),
  ('pacific reggae', 'pacificreggae'),
  ('pagan black metal', 'paganblackmetal'),
  ('pagan folk', 'paganfolk'),
  ('paghjella', 'paghjella'),
  ('pagodão', 'pagodao'),
  ('pagode', 'pagode'),
  ('pagode romântico', 'pagoderomantico'),
  ('paisley underground', 'paisleyunderground'),
  ('pala', 'pala'),
  ('palingsound', 'palingsound'),
  ('palm-wine', 'palmwine'),
  ('palo de mayo', 'palodemayo'),
  ('pandilla', 'pandilla'),
  ('pansori', 'pansori'),
  ('paramaribop', 'paramaribop'),
  ('parang', 'parang'),
  ('parlour music', 'parlourmusic'),
  ('partido alto', 'partidoalto'),
  ('partyschlager', 'partyschlager'),
  ('pasillo', 'pasillo'),
  ('pasodoble', 'pasodoble'),
  ('passion setting', 'passionsetting'),
  ('pásztordal', 'pasztordal'),
  ('payada', 'payada'),
  ('peak time techno', 'peaktimetechno'),
  ('pep band', 'pepband'),
  ('persian classical', 'persianclassical'),
  ('persian pop', 'persianpop'),
  ('philly club', 'phillyclub'),
  ('philly club rap', 'phillyclubrap'),
  ('philly drill', 'phillydrill'),
  ('philly soul', 'phillysoul'),
  ('phleng phuea chiwit', 'phlengphueachiwit'),
  ('phonk', 'phonk'),
  ('phonk house', 'phonkhouse'),
  ('piano blues', 'pianoblues'),
  ('piano rock', 'pianorock'),
  ('picopop', 'picopop'),
  ('piedmont blues', 'piedmontblues'),
  ('pigfuck', 'pigfuck'),
  ('pilón', 'pilon'),
  ('pimba', 'pimba'),
  ('pinpeat', 'pinpeat'),
  ('pìobaireachd', 'piobaireachd'),
  ('piosenka aktorska', 'piosenkaaktorska'),
  ('pipe band music', 'pipebandmusic'),
  ('piphat', 'piphat'),
  ('pirekua', 'pirekua'),
  ('piseiro', 'piseiro'),
  ('piyyut', 'piyyut'),
  ('pizzica', 'pizzica'),
  ('plainchant', 'plainchant'),
  ('plena', 'plena'),
  ('plugg', 'plugg'),
  ('pluggnb', 'pluggnb'),
  ('plunderphonics', 'plunderphonics'),
  ('poetry', 'poetry'),
  ('polca criolla', 'polcacriolla'),
  ('polifonia occitana', 'polifoniaoccitana'),
  ('political hip hop', 'politicalhiphop'),
  ('polka', 'polka'),
  ('polka paraguaya', 'polkaparaguaya'),
  ('polonaise', 'polonaise'),
  ('pon-chak disco', 'ponchakdisco'),
  ('pop', 'pop'),
  ('pop ghazal', 'popghazal'),
  ('pop kreatif', 'popkreatif'),
  ('pop metal', 'popmetal'),
  ('pop minang', 'popminang'),
  ('pop punk', 'poppunk'),
  ('pop raï', 'poprai'),
  ('pop rap', 'poprap'),
  ('pop rock', 'poprock'),
  ('pop screamo', 'popscreamo'),
  ('pop soul', 'popsoul'),
  ('pop yeh-yeh', 'popyehyeh'),
  ('porn groove', 'porngroove'),
  ('pornogrind', 'pornogrind'),
  ('porro', 'porro'),
  ('post-bop', 'postbop'),
  ('post-britpop', 'postbritpop'),
  ('post-classical', 'postclassical'),
  ('post-dubstep', 'postdubstep'),
  ('post-grunge', 'postgrunge'),
  ('post-hardcore', 'posthardcore'),
  ('post-industrial', 'postindustrial'),
  ('post-metal', 'postmetal'),
  ('post-minimalism', 'postminimalism'),
  ('post-punk', 'postpunk'),
  ('post-punk revival', 'postpunkrevival'),
  ('post-rock', 'postrock'),
  ('powada', 'powada'),
  ('power electronics', 'powerelectronics'),
  ('power metal', 'powermetal'),
  ('power noise', 'powernoise'),
  ('power pop', 'powerpop'),
  ('power soca', 'powersoca'),
  ('powerstomp', 'powerstomp'),
  ('powerviolence', 'powerviolence'),
  ('praise & worship', 'praiseandworship'),
  ('praise break', 'praisebreak'),
  ('prank calls', 'prankcalls'),
  ('prelude', 'prelude'),
  ('process music', 'processmusic'),
  ('production music', 'productionmusic'),
  ('progressive', 'progressive'),
  ('progressive bluegrass', 'progressivebluegrass'),
  ('progressive breaks', 'progressivebreaks'),
  ('progressive country', 'progressivecountry'),
  ('progressive electronic', 'progressiveelectronic'),
  ('progressive folk', 'progressivefolk'),
  ('progressive house', 'progressivehouse'),
  ('progressive metal', 'progressivemetal'),
  ('progressive metalcore', 'progressivemetalcore'),
  ('progressive pop', 'progressivepop'),
  ('progressive post-hardcore', 'progressiveposthardcore'),
  ('progressive psytrance', 'progressivepsytrance'),
  ('progressive rock', 'progressiverock'),
  ('progressive soul', 'progressivesoul'),
  ('progressive trance', 'progressivetrance'),
  ('proto-punk', 'protopunk'),
  ('psichedelia occulta italiana', 'psichedeliaoccultaitaliana'),
  ('psybient', 'psybient'),
  ('psybreaks', 'psybreaks'),
  ('psychedelic', 'psychedelic'),
  ('psychedelic folk', 'psychedelicfolk'),
  ('psychedelic pop', 'psychedelicpop'),
  ('psychedelic rock', 'psychedelicrock'),
  ('psychedelic soul', 'psychedelicsoul'),
  ('psychobilly', 'psychobilly'),
  ('psychploitation', 'psychploitation'),
  ('psycore', 'psycore'),
  ('psystyle', 'psystyle'),
  ('psytrance', 'psytrance'),
  ('pub rock', 'pubrock'),
  ('puirt à beul', 'puirtabeul'),
  ('pumpcore', 'pumpcore'),
  ('pungmul', 'pungmul'),
  ('punk', 'punk'),
  ('punk blues', 'punkblues'),
  ('punk poetry', 'punkpoetry'),
  ('punk rap', 'punkrap'),
  ('punk rock', 'punkrock'),
  ('punta', 'punta'),
  ('punto', 'punto'),
  ('purple sound', 'purplesound'),
  ('puxa', 'puxa'),
  ('q-pop', 'qpop'),
  ('qaraami', 'qaraami'),
  ('qasidah modern', 'qasidahmodern'),
  ('qawwali', 'qawwali'),
  ('quan họ', 'quanho'),
  ('queercore', 'queercore'),
  ('quiet storm', 'quietstorm'),
  ('quyi', 'quyi'),
  ('r&b', 'randb'),
  ('rabbit song', 'rabbitsong'),
  ('rabiz', 'rabiz'),
  ('raga rock', 'ragarock'),
  ('rage', 'rage'),
  ('ragga', 'ragga'),
  ('ragga hip-hop', 'raggahiphop'),
  ('ragga jungle', 'raggajungle'),
  ('raggacore', 'raggacore'),
  ('raggatek', 'raggatek'),
  ('ragtime', 'ragtime'),
  ('ragtime song', 'ragtimesong'),
  ('raï', 'rai'),
  ('rain sounds', 'rainsounds'),
  ('ranchera', 'ranchera'),
  ('rap metal', 'rapmetal'),
  ('rap rock', 'raprock'),
  ('rapcore', 'rapcore'),
  ('rapso', 'rapso'),
  ('raqs baladi', 'raqsbaladi'),
  ('rara', 'rara'),
  ('rasin', 'rasin'),
  ('rasqueado cuiabano', 'rasqueadocuiabano'),
  ('rasteirinha', 'rasteirinha'),
  ('ratchet music', 'ratchetmusic'),
  ('rautalanka', 'rautalanka'),
  ('rave', 'rave'),
  ('raw punk', 'rawpunk'),
  ('rawphoric', 'rawphoric'),
  ('rawstyle', 'rawstyle'),
  ('rebetiko', 'rebetiko'),
  ('red dirt', 'reddirt'),
  ('red disco', 'reddisco'),
  ('red song', 'redsong'),
  ('reductionism', 'reductionism'),
  ('regalia', 'regalia'),
  ('reggae', 'reggae'),
  ('reggae panameño', 'reggaepanameno'),
  ('reggae rock', 'reggaerock'),
  ('reggae-pop', 'reggaepop'),
  ('reggaeton', 'reggaeton'),
  ('regional mexicano', 'regionalmexicano'),
  ('renaissance', 'renaissance'),
  ('reparto', 'reparto'),
  ('repente', 'repente'),
  ('requiem', 'requiem'),
  ('revue', 'revue'),
  ('rhumba', 'rhumba'),
  ('ricercar', 'ricercar'),
  ('riddim dubstep', 'riddimdubstep'),
  ('rigsar', 'rigsar'),
  ('ring shout', 'ringshout'),
  ('riot grrrl', 'riotgrrrl'),
  ('ripsaw', 'ripsaw'),
  ('ritmada', 'ritmada'),
  ('ritual ambient', 'ritualambient'),
  ('rizitika', 'rizitika'),
  ('rkt', 'rkt'),
  ('rock', 'rock'),
  ('rock and roll', 'rockandroll'),
  ('rock andaluz', 'rockandaluz'),
  ('rock andino', 'rockandino'),
  ('rock jiwang', 'rockjiwang'),
  ('rock kapak', 'rockkapak'),
  ('rock musical', 'rockmusical'),
  ('rock opera', 'rockopera'),
  ('rock rural', 'rockrural'),
  ('rock urbano', 'rockurbano'),
  ('rock urbano mexicano', 'rockurbanomexicano'),
  ('rockaballad', 'rockaballad'),
  ('rockabilly', 'rockabilly'),
  ('rocksteady', 'rocksteady'),
  ('rōkyoku', 'rokyoku'),
  ('rom kbach', 'romkbach'),
  ('romanian popcorn', 'romanianpopcorn'),
  ('romantic classical', 'romanticclassical'),
  ('romantic flow', 'romanticflow'),
  ('romantische oper', 'romantischeoper'),
  ('rominimal', 'rominimal'),
  ('roots reggae', 'rootsreggae'),
  ('roots rock', 'rootsrock'),
  ('rumba', 'rumba'),
  ('rumba catalana', 'rumbacatalana'),
  ('rumba cubana', 'rumbacubana'),
  ('rumba flamenca', 'rumbaflamenca'),
  ('runo song', 'runosong'),
  ('russian chanson', 'russianchanson'),
  ('russian orthodox liturgical music', 'russianorthodoxliturgicalmusic'),
  ('russian romance', 'russianromance'),
  ('rustic stomp', 'rusticstomp'),
  ('ryūkōka', 'ryukoka'),
  ('sa''idi', 'saidi'),
  ('sacred harp', 'sacredharp'),
  ('sacred steel', 'sacredsteel'),
  ('saeta', 'saeta'),
  ('salegy', 'salegy'),
  ('salsa', 'salsa'),
  ('salsa choke', 'salsachoke'),
  ('salsa dura', 'salsadura'),
  ('salsa romántica', 'salsaromantica'),
  ('saluang klasik', 'saluangklasik'),
  ('samba', 'samba'),
  ('samba de breque', 'sambadebreque'),
  ('samba de gafieira', 'sambadegafieira'),
  ('samba de roda', 'sambaderoda'),
  ('samba de terreiro', 'sambadeterreiro'),
  ('samba rap', 'sambarap'),
  ('samba soul', 'sambasoul'),
  ('samba-canção', 'sambacancao'),
  ('samba-choro', 'sambachoro'),
  ('samba-enredo', 'sambaenredo'),
  ('samba-exaltação', 'sambaexaltacao'),
  ('samba-jazz', 'sambajazz'),
  ('samba-joia', 'sambajoia'),
  ('samba-reggae', 'sambareggae'),
  ('samba-rock', 'sambarock'),
  ('sambalanço', 'sambalanco'),
  ('sambass', 'sambass'),
  ('sample drill', 'sampledrill'),
  ('sampledelia', 'sampledelia'),
  ('samri', 'samri'),
  ('sanjo', 'sanjo'),
  ('sanjuanito', 'sanjuanito'),
  ('santé engagé', 'santeengage'),
  ('sarala gee', 'saralagee'),
  ('sardana', 'sardana'),
  ('sarum chant', 'sarumchant'),
  ('sasscore', 'sasscore'),
  ('sawt', 'sawt'),
  ('saya afroboliviana', 'sayaafroboliviana'),
  ('scam rap', 'scamrap'),
  ('schlager', 'schlager'),
  ('schottische', 'schottische'),
  ('schranz', 'schranz'),
  ('scottish country dance music', 'scottishcountrydancemusic'),
  ('screamo', 'screamo'),
  ('scrumpy and western', 'scrumpyandwestern'),
  ('sea shanty', 'seashanty'),
  ('sean-nós', 'seannos'),
  ('seapunk', 'seapunk'),
  ('séga', 'sega'),
  ('séga tambour', 'segatambour'),
  ('seggae', 'seggae'),
  ('seguidilla', 'seguidilla'),
  ('seishun punk', 'seishunpunk'),
  ('semba', 'semba'),
  ('semi-trot', 'semitrot'),
  ('serenade', 'serenade'),
  ('seresta', 'seresta'),
  ('serialism', 'serialism'),
  ('sermon', 'sermon'),
  ('sertanejo', 'sertanejo'),
  ('sertanejo raiz', 'sertanejoraiz'),
  ('sertanejo romântico', 'sertanejoromantico'),
  ('sertanejo universitário', 'sertanejouniversitario'),
  ('seto leelo', 'setoleelo'),
  ('sevdalinka', 'sevdalinka'),
  ('sevillanas', 'sevillanas'),
  ('sexy drill', 'sexydrill'),
  ('shaabi', 'shaabi'),
  ('shabad kirtan', 'shabadkirtan'),
  ('shan''ge', 'shange'),
  ('shangaan electro', 'shangaanelectro'),
  ('shanto', 'shanto'),
  ('shashmaqam', 'shashmaqam'),
  ('shatta', 'shatta'),
  ('shibuya-kei', 'shibuyakei'),
  ('shidaiqu', 'shidaiqu'),
  ('shima-uta', 'shimauta'),
  ('shinkyoku', 'shinkyoku'),
  ('shitgaze', 'shitgaze'),
  ('shoegaze', 'shoegaze'),
  ('shōmyō', 'shomyo'),
  ('shoor', 'shoor'),
  ('sichuan opera', 'sichuanopera'),
  ('sierreño', 'sierreno'),
  ('sigidrigi', 'sigidrigi'),
  ('sigilkore', 'sigilkore'),
  ('sikuri', 'sikuri'),
  ('sinawi', 'sinawi'),
  ('sinfonia concertante', 'sinfoniaconcertante'),
  ('singeli', 'singeli'),
  ('singer-songwriter', 'singersongwriter'),
  ('singspiel', 'singspiel'),
  ('sissy bounce', 'sissybounce'),
  ('sitarsploitation', 'sitarsploitation'),
  ('sizhu music', 'sizhumusic'),
  ('ska', 'ska'),
  ('ska punk', 'skapunk'),
  ('skacore', 'skacore'),
  ('skate punk', 'skatepunk'),
  ('sketch comedy', 'sketchcomedy'),
  ('skiffle', 'skiffle'),
  ('skiladiko', 'skiladiko'),
  ('skinhead reggae', 'skinheadreggae'),
  ('skizzo', 'skizzo'),
  ('skullstep', 'skullstep'),
  ('skweee', 'skweee'),
  ('slack-key guitar', 'slackkeyguitar'),
  ('slacker rock', 'slackerrock'),
  ('slam death metal', 'slamdeathmetal'),
  ('slam poetry', 'slampoetry'),
  ('slap house', 'slaphouse'),
  ('sleaze rock', 'sleazerock'),
  ('slimepunk', 'slimepunk'),
  ('slow waltz', 'slowwaltz'),
  ('slowcore', 'slowcore'),
  ('slowed & reverb', 'slowedandreverb'),
  ('sludge metal', 'sludgemetal'),
  ('slushwave', 'slushwave'),
  ('smooth jazz', 'smoothjazz'),
  ('smooth soul', 'smoothsoul'),
  ('snap', 'snap'),
  ('soca', 'soca'),
  ('soft rock', 'softrock'),
  ('soft visual', 'softvisual'),
  ('sōkyoku', 'sokyoku'),
  ('son calentano', 'soncalentano'),
  ('son cubano', 'soncubano'),
  ('son de pascua', 'sondepascua'),
  ('son huasteco', 'sonhuasteco'),
  ('son istmeño', 'sonistmeno'),
  ('son jarocho', 'sonjarocho'),
  ('son montuno', 'sonmontuno'),
  ('son nica', 'sonnica'),
  ('sonata', 'sonata'),
  ('songo', 'songo'),
  ('sonorism', 'sonorism'),
  ('sophisti-pop', 'sophistipop'),
  ('soukous', 'soukous'),
  ('soul', 'soul'),
  ('soul blues', 'soulblues'),
  ('soul jazz', 'souljazz'),
  ('sound art', 'soundart'),
  ('sound collage', 'soundcollage'),
  ('sound effects', 'soundeffects'),
  ('sound poetry', 'soundpoetry'),
  ('southeast asian classical', 'southeastasianclassical'),
  ('southern gospel', 'southerngospel'),
  ('southern hip hop', 'southernhiphop'),
  ('southern metal', 'southernmetal'),
  ('southern rock', 'southernrock'),
  ('southern soul', 'southernsoul'),
  ('sovietwave', 'sovietwave'),
  ('space age pop', 'spaceagepop'),
  ('space ambient', 'spaceambient'),
  ('space disco', 'spacedisco'),
  ('space rock', 'spacerock'),
  ('space rock revival', 'spacerockrevival'),
  ('spacesynth', 'spacesynth'),
  ('spamwave', 'spamwave'),
  ('spectralism', 'spectralism'),
  ('speech', 'speech'),
  ('speed garage', 'speedgarage'),
  ('speed house', 'speedhouse'),
  ('speed metal', 'speedmetal'),
  ('speedcore', 'speedcore'),
  ('spiritual art song', 'spiritualartsong'),
  ('spiritual jazz', 'spiritualjazz'),
  ('spirituals', 'spirituals'),
  ('splittercore', 'splittercore'),
  ('spoken word', 'spokenword'),
  ('spouge', 'spouge'),
  ('staïfi', 'staifi'),
  ('standup comedy', 'standupcomedy'),
  ('steampunk', 'steampunk'),
  ('steel band', 'steelband'),
  ('stenchcore', 'stenchcore'),
  ('sticheron', 'sticheron'),
  ('stochastic music', 'stochasticmusic'),
  ('stomp and holler', 'stompandholler'),
  ('stoner metal', 'stonermetal'),
  ('stoner rap', 'stonerrap'),
  ('stoner rock', 'stonerrock'),
  ('stornello', 'stornello'),
  ('street punk', 'streetpunk'),
  ('stride', 'stride'),
  ('string quartet', 'stringquartet'),
  ('stutter house', 'stutterhouse'),
  ('sufi rock', 'sufirock'),
  ('sufiana kalam', 'sufianakalam'),
  ('sundanese pop', 'sundanesepop'),
  ('sungura', 'sungura'),
  ('sunshine pop', 'sunshinepop'),
  ('suomisaundi', 'suomisaundi'),
  ('surf', 'surf'),
  ('surf punk', 'surfpunk'),
  ('surf rock', 'surfrock'),
  ('sutartinės', 'sutartines'),
  ('swamp blues', 'swampblues'),
  ('swamp pop', 'swamppop'),
  ('swamp rock', 'swamprock'),
  ('swancore', 'swancore'),
  ('sweet jazz', 'sweetjazz'),
  ('swing', 'swing'),
  ('swing revival', 'swingrevival'),
  ('symphonic black metal', 'symphonicblackmetal'),
  ('symphonic metal', 'symphonicmetal'),
  ('symphonic mugham', 'symphonicmugham'),
  ('symphonic poem', 'symphonicpoem'),
  ('symphonic prog', 'symphonicprog'),
  ('symphonic rock', 'symphonicrock'),
  ('symphony', 'symphony'),
  ('synth funk', 'synthfunk'),
  ('synth-pop', 'synthpop'),
  ('synthwave', 'synthwave'),
  ('t-pop', 'tpop'),
  ('taarab', 'taarab'),
  ('tajaraste', 'tajaraste'),
  ('takamba', 'takamba'),
  ('talempong', 'talempong'),
  ('talempong goyang', 'talemponggoyang'),
  ('talking blues', 'talkingblues'),
  ('tallava', 'tallava'),
  ('tamborera', 'tamborera'),
  ('tamborito', 'tamborito'),
  ('tamborzão', 'tamborzao'),
  ('tammurriata', 'tammurriata'),
  ('tân cổ giao duyên', 'tancogiaoduyen'),
  ('tango', 'tango'),
  ('tanjidor', 'tanjidor'),
  ('taoist ritual music', 'taoistritualmusic'),
  ('tape music', 'tapemusic'),
  ('tappa', 'tappa'),
  ('taquirari', 'taquirari'),
  ('tarana', 'tarana'),
  ('tarantella', 'tarantella'),
  ('tarawangsa', 'tarawangsa'),
  ('tarraxinha', 'tarraxinha'),
  ('tassa', 'tassa'),
  ('tassu', 'tassu'),
  ('tbm', 'tbm'),
  ('tchinkoumé', 'tchinkoume'),
  ('tearout', 'tearout'),
  ('tearout brostep', 'tearoutbrostep'),
  ('tech house', 'techhouse'),
  ('tech trance', 'techtrance'),
  ('technical death metal', 'technicaldeathmetal'),
  ('technical thrash metal', 'technicalthrashmetal'),
  ('techno', 'techno'),
  ('techno bass', 'technobass'),
  ('techno kayō', 'technokayo'),
  ('technobanda', 'technobanda'),
  ('technoid', 'technoid'),
  ('techstep', 'techstep'),
  ('tecnobrega', 'tecnobrega'),
  ('tecnocumbia', 'tecnocumbia'),
  ('tecnofunk', 'tecnofunk'),
  ('tecnomerengue', 'tecnomerengue'),
  ('tecnorumba', 'tecnorumba'),
  ('teen pop', 'teenpop'),
  ('tejano', 'tejano'),
  ('tembang cianjuran', 'tembangcianjuran'),
  ('terror plugg', 'terrorplugg'),
  ('terrorcore', 'terrorcore'),
  ('tex-mex', 'texmex'),
  ('texas blues', 'texasblues'),
  ('texas country', 'texascountry'),
  ('thai classical', 'thaiclassical'),
  ('thall', 'thall'),
  ('theme and variations', 'themeandvariations'),
  ('third stream', 'thirdstream'),
  ('third wave ska', 'thirdwaveska'),
  ('thrash metal', 'thrashmetal'),
  ('thrashcore', 'thrashcore'),
  ('thumri', 'thumri'),
  ('tibetan buddhist chant', 'tibetanbuddhistchant'),
  ('tiento', 'tiento'),
  ('timba', 'timba'),
  ('timbila', 'timbila'),
  ('tin pan alley', 'tinpanalley'),
  ('tivaner inngernerlu', 'tivanerinngernerlu'),
  ('tizita', 'tizita'),
  ('toada de boi', 'toadadeboi'),
  ('toccata', 'toccata'),
  ('tonada asturiana', 'tonadaasturiana'),
  ('tonada potosina', 'tonadapotosina'),
  ('tonadilla', 'tonadilla'),
  ('tondero', 'tondero'),
  ('tontipop', 'tontipop'),
  ('totalism', 'totalism'),
  ('tough guy hardcore', 'toughguyhardcore'),
  ('township bubblegum', 'townshipbubblegum'),
  ('township jive', 'townshipjive'),
  ('toypop', 'toypop'),
  ('toytown pop', 'toytownpop'),
  ('toytown techno', 'toytowntechno'),
  ('tradi-moderne congolais', 'tradimodernecongolais'),
  ('tradi-moderne ivoirien', 'tradimoderneivoirien'),
  ('traditional black gospel', 'traditionalblackgospel'),
  ('traditional bluegrass', 'traditionalbluegrass'),
  ('traditional country', 'traditionalcountry'),
  ('traditional doom metal', 'traditionaldoommetal'),
  ('traditional pop', 'traditionalpop'),
  ('traditional séga', 'traditionalsega'),
  ('tragédie en musique', 'tragedieenmusique'),
  ('trallalero', 'trallalero'),
  ('trampská hudba', 'trampskahudba'),
  ('trance', 'trance'),
  ('trance 2.0', 'trance20'),
  ('trance metal', 'trancemetal'),
  ('trancestep', 'trancestep'),
  ('trap', 'trap'),
  ('trap dancehall', 'trapdancehall'),
  ('trap edm', 'trapedm'),
  ('trap latino', 'traplatino'),
  ('trap metal', 'trapmetal'),
  ('trap shaabi', 'trapshaabi'),
  ('trap soul', 'trapsoul'),
  ('trapfunk', 'trapfunk'),
  ('tread', 'tread'),
  ('tribal ambient', 'tribalambient'),
  ('tribal guarachero', 'tribalguarachero'),
  ('tribal house', 'tribalhouse'),
  ('trikitixa', 'trikitixa'),
  ('trip hop', 'triphop'),
  ('troparion', 'troparion'),
  ('tropical house', 'tropicalhouse'),
  ('tropical rock', 'tropicalrock'),
  ('tropicália', 'tropicalia'),
  ('tropicanibalismo', 'tropicanibalismo'),
  ('tropipop', 'tropipop'),
  ('trot', 'trot'),
  ('troubadour song', 'troubadoursong'),
  ('trova', 'trova'),
  ('trova yucateca', 'trovayucateca'),
  ('truck driving country', 'truckdrivingcountry'),
  ('tsapiky', 'tsapiky'),
  ('tsonga disco', 'tsongadisco'),
  ('tsugaru-jamisen', 'tsugarujamisen'),
  ('tumba', 'tumba'),
  ('tumba francesa', 'tumbafrancesa'),
  ('tumbélé', 'tumbele'),
  ('turbo-folk', 'turbofolk'),
  ('turkish classical', 'turkishclassical'),
  ('turkish folk', 'turkishfolk'),
  ('turkish pop', 'turkishpop'),
  ('turntablism', 'turntablism'),
  ('twee pop', 'tweepop'),
  ('twerk', 'twerk'),
  ('twoubadou', 'twoubadou'),
  ('uaajeerneq', 'uaajeerneq'),
  ('udigrudi', 'udigrudi'),
  ('uk drill', 'ukdrill'),
  ('uk funky', 'ukfunky'),
  ('uk garage', 'ukgarage'),
  ('uk hardcore', 'ukhardcore'),
  ('uk jackin', 'ukjackin'),
  ('uk street soul', 'ukstreetsoul'),
  ('uk82', 'uk82'),
  ('unakesa', 'unakesa'),
  ('underground hip hop', 'undergroundhiphop'),
  ('unyago', 'unyago'),
  ('upopo', 'upopo'),
  ('uptempo hardcore', 'uptempohardcore'),
  ('urban contemporary gospel', 'urbancontemporarygospel'),
  ('urban cowboy', 'urbancowboy'),
  ('urtiin duu', 'urtiinduu'),
  ('urumi melam', 'urumimelam'),
  ('us power metal', 'uspowermetal'),
  ('utopian virtual', 'utopianvirtual'),
  ('uyghur muqam', 'uyghurmuqam'),
  ('uzun hava', 'uzunhava'),
  ('v-pop', 'vpop'),
  ('vaigat', 'vaigat'),
  ('valaam chant', 'valaamchant'),
  ('vallenato', 'vallenato'),
  ('vals criollo', 'valscriollo'),
  ('vals venezolano', 'valsvenezolano'),
  ('valsa brasileira', 'valsabrasileira'),
  ('vanera', 'vanera'),
  ('vapornoise', 'vapornoise'),
  ('vaportrap', 'vaportrap'),
  ('vaporwave', 'vaporwave'),
  ('vaudeville', 'vaudeville'),
  ('vaudeville blues', 'vaudevilleblues'),
  ('vedic chant', 'vedicchant'),
  ('verbunkos', 'verbunkos'),
  ('verismo', 'verismo'),
  ('vietnamese bolero', 'vietnamesebolero'),
  ('vietnamese classical', 'vietnameseclassical'),
  ('viking metal', 'vikingmetal'),
  ('viking rock', 'vikingrock'),
  ('villancico', 'villancico'),
  ('vinahouse', 'vinahouse'),
  ('visa', 'visa'),
  ('visual kei', 'visualkei'),
  ('vocal house', 'vocalhouse'),
  ('vocal jazz', 'vocaljazz'),
  ('vocal surf', 'vocalsurf'),
  ('vocal trance', 'vocaltrance'),
  ('vocalese', 'vocalese'),
  ('volkstümliche musik', 'volkstumlichemusik'),
  ('vude', 'vude'),
  ('wa euro', 'waeuro'),
  ('waila', 'waila'),
  ('waka', 'waka'),
  ('waltz', 'waltz'),
  ('wangga', 'wangga'),
  ('war metal', 'warmetal'),
  ('wassoulou', 'wassoulou'),
  ('waulking song', 'waulkingsong'),
  ('wave', 'wave'),
  ('weightless', 'weightless'),
  ('west coast breaks', 'westcoastbreaks'),
  ('west coast hip hop', 'westcoasthiphop'),
  ('west coast swing', 'westcoastswing'),
  ('western', 'western'),
  ('western classical', 'westernclassical'),
  ('western swing', 'westernswing'),
  ('whale song', 'whalesong'),
  ('whistling', 'whistling'),
  ('white voice', 'whitevoice'),
  ('winter synth', 'wintersynth'),
  ('witch house', 'witchhouse'),
  ('wong shadow', 'wongshadow'),
  ('wonky', 'wonky'),
  ('wonky techno', 'wonkytechno'),
  ('work song', 'worksong'),
  ('world fusion', 'worldfusion'),
  ('worldbeat', 'worldbeat'),
  ('wyrd folk', 'wyrdfolk'),
  ('xẩm', 'xam'),
  ('xaxado', 'xaxado'),
  ('xian psych', 'xianpsych'),
  ('xote', 'xote'),
  ('xtra raw', 'xtraraw'),
  ('xuc', 'xuc'),
  ('yacht rock', 'yachtrock'),
  ('yakousei', 'yakousei'),
  ('yangzhou opera', 'yangzhouopera'),
  ('yanyue', 'yanyue'),
  ('yaraví', 'yaravi'),
  ('yayue', 'yayue'),
  ('yé-yé', 'yeye'),
  ('yodeling', 'yodeling'),
  ('ytpmv', 'ytpmv'),
  ('yu-mex', 'yumex'),
  ('yue opera', 'yueopera'),
  ('yukar', 'yukar'),
  ('zamacueca', 'zamacueca'),
  ('zamba', 'zamba'),
  ('zamrock', 'zamrock'),
  ('zarzuela', 'zarzuela'),
  ('zarzuela barroca', 'zarzuelabarroca'),
  ('zeitoper', 'zeitoper'),
  ('zema', 'zema'),
  ('zemirot', 'zemirot'),
  ('zenonesque', 'zenonesque'),
  ('zess', 'zess'),
  ('zeuhl', 'zeuhl'),
  ('zeybek', 'zeybek'),
  ('zhongguo feng', 'zhongguofeng'),
  ('ziglibithy', 'ziglibithy'),
  ('zinli', 'zinli'),
  ('znamenny chant', 'znamennychant'),
  ('zoblazo', 'zoblazo'),
  ('zohioliin duu', 'zohioliinduu'),
  ('zolo', 'zolo'),
  ('zouglou', 'zouglou'),
  ('zouk', 'zouk'),
  ('zouk love', 'zouklove'),
  ('zydeco', 'zydeco')
ON CONFLICT DO NOTHING;
