/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The user's queued Spotify lookups
         * @description Background catalog lookups still queued for this user, e.g. after an import.
         */
        get: operations["getJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/cron/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync every user's recent plays
         * @description Called by a hosted scheduler (GitHub Actions, once deployed). Authenticates with `Authorization: Bearer <CRON_SECRET>`, not a user session.
         */
        post: operations["pollAllUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish the Spotify login
         * @description Exchanges the PKCE authorization code for tokens, stores them encrypted, and starts a session (sets the `rc_session` cookie).
         */
        post: operations["completeLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Ends the session, if there is one, and clears the cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pull recent plays from Spotify
         * @description Records the user's recently played tracks. Within 30 s of the last sync it returns `skipped` without calling Spotify. `missedPlays` means more than Spotify's last 50 plays happened since the previous sync, so there is a gap (see `/history/gaps`).
         */
        post: operations["syncHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gaps in the history
         * @description Unfilled stretches where plays may be missing, newest first. An import fills them.
         */
        get: operations["listGaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/plays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Play history
         * @description Newest first. Pass `nextCursor` back as `before` for the next page.
         */
        get: operations["listPlays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A track with your play stats
         * @description Where you played it from, recent plays, and which of your playlists hold it.
         */
        get: operations["getTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tracks a rule would pick
         * @description Lets the user check the tracks before creating anything. Nothing is written.
         */
        post: operations["previewPlaylistRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your playlists
         * @description In your Spotify order, with how often you play from each.
         */
        get: operations["listPlaylists"];
        put?: never;
        /**
         * Create a playlist
         * @description Creates it on Spotify with the given tracks, then records it here.
         */
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add tracks
         * @description Appends, or inserts at `position`. Only playlists the user owns or collaborates on.
         */
        post: operations["addPlaylistItems"];
        /**
         * Remove tracks
         * @description Removes every occurrence of each track.
         */
        delete: operations["removePlaylistItems"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/{id}/items/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Move a track
         * @description Moves the track at `from` so it ends up at `to` (0-based positions).
         */
        put: operations["movePlaylistItem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync playlists from Spotify
         * @description Refreshes every playlist's details, then fetches tracks for playlists that changed, within a time budget. Call again while `remaining > 0`.
         */
        post: operations["syncPlaylists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A playlist and its tracks
         * @description Each track with your play counts and the other playlists that hold it.
         */
        get: operations["getPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Totals and listening over time
         * @description Each point splits plays into new tracks (a track's first-ever play) and replays. Ranges over 90 days are bucketed by week, shorter ones by day, in the user's time zone; empty buckets are zeros.
         */
        get: operations["getStatsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Most played tracks, artists or albums
         * @description Ranked by play count or listening time. Plays without a known duration count the track length.
         */
        get: operations["getStatsTop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/spotify-top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spotify's own top tracks or artists
         * @description Spotify's ranking, next to the plays Replay Crate has recorded for each, for comparison.
         */
        get: operations["getSpotifyTop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an import
         * @description Step 1 of 3. The browser parses the Extended Streaming History export and uploads only timestamp, play time and track id: create, add plays (in chunks), finish.
         */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}/plays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a chunk of plays
         * @description Step 2 of 3. Up to 5000 plays per request; call as often as needed.
         */
        post: operations["addImportPlays"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish an import
         * @description Step 3 of 3. Plays of known tracks move into the history now; unknown tracks are queued for lookup and their plays follow. Closes any history gap the import covers.
         */
        post: operations["finishImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress of the latest import */
        get: operations["getLatestImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InternalError: {
            /** @enum {string} */
            error: "internal_error";
            /** @description Matches X-Request-Id and the server log. */
            requestId: string;
        };
        UnauthorizedError: {
            /** @enum {string} */
            error: "unauthorized";
        };
        /** @description CRON_SECRET is not set. */
        CronDisabledError: {
            /** @enum {string} */
            error: "cron_disabled";
        };
        Me: {
            /**
             * @description Spotify user id.
             * @example pixelg
             */
            id: string;
            displayName: string | null;
            imageUrl: string | null;
            /** @description Spotify refused the refresh token; reconnect to keep syncing. */
            needsReauth: boolean;
            /**
             * @description Scopes the app now asks for that this user never granted (the app added features since they connected). Reconnecting grants them; what worked before keeps working meanwhile.
             * @example [
             *       "user-read-playback-state"
             *     ]
             */
            missingScopes: string[];
        };
        InvalidRequestError: {
            /** @enum {string} */
            error: "invalid_request";
            issues: {
                path: string;
                message: string;
            }[];
        };
        /** @description The login's redirect URI isn't the one this server is configured with. */
        RedirectUriMismatchError: {
            /** @enum {string} */
            error: "redirect_uri_mismatch";
        };
        SpotifyAuthFailedError: {
            /** @enum {string} */
            error: "spotify_auth_failed";
            /** @description Spotify's OAuth error, e.g. invalid_grant. */
            detail: string;
        };
        /** @description Spotify completed the login without a refresh token. */
        MissingRefreshTokenError: {
            /** @enum {string} */
            error: "missing_refresh_token";
        };
        /** @description Spotify refused the refresh token; the user must reconnect. */
        ReauthRequiredError: {
            /** @enum {string} */
            error: "reauth_required";
        };
        RateLimitedError: {
            /** @enum {string} */
            error: "rate_limited";
            /** @description Seconds to wait, when Spotify said. */
            retryAfter: number | null;
        };
        HistoryGap: {
            id: number;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            after: string;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            before: string;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            detectedAt: string;
        };
        PlayItem: {
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            playedAt: string;
            /** @description Known for imported plays; null for polled ones. */
            msPlayed: number | null;
            /** @enum {string} */
            source: "poll" | "import";
            context: components["schemas"]["ContextRef"];
            track: {
                /** @description Spotify track id. */
                id: string;
                name: string;
                durationMs: number;
                explicit: boolean;
                album: {
                    id: string;
                    name: string;
                    thumbUrl: string | null;
                };
                artists: components["schemas"]["ArtistRef"][];
            };
        };
        ContextRef: {
            /** @example playlist */
            type: string;
            /** @example spotify:playlist:37i9dQZF1DXcBWIGoYBM5M */
            uri: string;
            name: string | null;
            imageUrl: string | null;
        } | null;
        ArtistRef: {
            id: string;
            name: string;
        };
        TrackDetail: {
            track: {
                id: string;
                name: string;
                durationMs: number;
                explicit: boolean;
                album: {
                    id: string;
                    name: string;
                    imageUrl: string | null;
                    /** @description Spotify's precision: YYYY, YYYY-MM or YYYY-MM-DD. */
                    releaseDate: string | null;
                };
                artists: components["schemas"]["ArtistRef"][];
            };
            stats: {
                playCount: number;
                /**
                 * Format: date-time
                 * @example 2026-09-21T12:00:00.000Z
                 */
                firstPlayedAt: string | null;
                /**
                 * Format: date-time
                 * @example 2026-09-21T12:00:00.000Z
                 */
                lastPlayedAt: string | null;
            };
            playedFrom: {
                context: components["schemas"]["ContextRef"];
                playCount: number;
                /**
                 * Format: date-time
                 * @example 2026-09-21T12:00:00.000Z
                 */
                lastPlayedAt: string | null;
            }[];
            recentPlays: {
                /**
                 * Format: date-time
                 * @example 2026-09-21T12:00:00.000Z
                 */
                playedAt: string;
                context: components["schemas"]["ContextRef"];
            }[];
            /** @description The user's playlists holding this track, in their Spotify order. */
            playlists: {
                id: string;
                name: string;
                thumbUrl: string | null;
            }[];
        };
        NotFoundError: {
            /** @enum {string} */
            error: "not_found";
        };
        ForbiddenError: {
            /** @enum {string} */
            error: "forbidden";
            message?: string;
        };
        PlaylistSummary: {
            id: string;
            name: string;
            thumbUrl: string | null;
            ownerName: string | null;
            owned: boolean;
            collaborative: boolean;
            isPublic: boolean | null;
            itemCount: number;
            /** @description Plays with this playlist as their context. */
            playsFrom: number;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            lastPlayedFrom: string | null;
        };
        PlaylistTrack: {
            position: number;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            addedAt: string | null;
            track: {
                id: string;
                name: string;
                durationMs: number;
                explicit: boolean;
                album: {
                    id: string;
                    name: string;
                    thumbUrl: string | null;
                };
                artists: components["schemas"]["ArtistRef"][];
            };
            playCount: number;
            /** @description Plays from this playlist. */
            playsHere: number;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            lastPlayedAt: string | null;
            alsoOn: {
                id: string;
                name: string;
            }[];
        };
        /**
         * @description A rolling window ending now.
         * @enum {string}
         */
        StatsRange: "7d" | "30d" | "90d" | "1y" | "all";
        TopItem: {
            rank: number;
            id: string;
            name: string;
            /** @description Artists, for tracks and albums. */
            subtitle: string | null;
            imageUrl: string | null;
            plays: number;
            minutes: number;
        };
        SpotifyTopItem: {
            rank: number;
            id: string;
            name: string;
            subtitle: string | null;
            imageUrl: string | null;
            /** @description Plays Replay Crate has recorded. */
            plays: number;
        };
        /** @description The import was already finished; start a new one. */
        AlreadyFinishedError: {
            /** @enum {string} */
            error: "already_finished";
        };
        ImportedPlay: {
            /**
             * Format: date-time
             * @description When the play ended, from the export.
             * @example 2026-09-21T12:00:00.000Z
             */
            ts: string;
            /** @description Milliseconds played. */
            ms: number;
            /** @description Spotify track id. */
            trackId: string;
        };
        /** @description null if there has never been an import. */
        ImportStatus: {
            id: number;
            playCount: number;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            earliest: string | null;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            latest: string | null;
            /** @description Plays of tracks Spotify no longer has. */
            unavailable: number;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-09-21T12:00:00.000Z
             */
            uploadedAt: string | null;
            /** @description Plays still waiting for their track's details. */
            waitingPlays: number;
            /** @description Tracks still to look up on Spotify. */
            tracksToFetch: number;
            done: boolean;
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Jobs waiting to run. */
                        pending: number;
                        /** @description Of those, jobs that have failed at least once. */
                        failing: number;
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    pollAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One result per connected user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: ({
                            userId: string;
                            inserted: number;
                        } | {
                            userId: string;
                            /** @enum {string} */
                            error: "reauth_required" | "failed";
                        })[];
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description cron_disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronDisabledError"];
                };
            };
        };
    };
    completeLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    codeVerifier: string;
                    /** Format: uri */
                    redirectUri: string;
                };
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description invalid_request | redirect_uri_mismatch | spotify_auth_failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"] | components["schemas"]["RedirectUriMismatchError"] | components["schemas"]["SpotifyAuthFailedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description missing_refresh_token */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingRefreshTokenError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    syncHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synced, or skipped because the last sync was moments ago. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "synced" | "skipped";
                        inserted: number;
                        /**
                         * Format: date-time
                         * @example 2026-09-21T12:00:00.000Z
                         */
                        lastSyncedAt: string;
                        missedPlays: boolean;
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    listGaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open gaps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        gaps: components["schemas"]["HistoryGap"][];
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    listPlays: {
        parameters: {
            query?: {
                /** @description Only plays strictly older than this. */
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of plays. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PlayItem"][];
                        /**
                         * Format: date-time
                         * @description null on the last page.
                         * @example 2026-09-21T12:00:00.000Z
                         */
                        nextCursor: string | null;
                        /**
                         * Format: date-time
                         * @example 2026-09-21T12:00:00.000Z
                         */
                        lastSyncedAt: string | null;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spotify track id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The track. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetail"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    previewPlaylistRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rule: {
                        /** @enum {string} */
                        kind: "top";
                        /**
                         * @default 30d
                         * @enum {string}
                         */
                        range?: "7d" | "30d" | "90d" | "1y" | "all";
                        /** @default 50 */
                        limit?: number;
                    } | {
                        /** @enum {string} */
                        kind: "recent";
                        /**
                         * @default 7d
                         * @enum {string}
                         */
                        range?: "7d" | "30d" | "90d" | "1y" | "all";
                        /** @default 50 */
                        limit?: number;
                    } | {
                        /** @enum {string} */
                        kind: "on_repeat";
                        /** @default 50 */
                        limit?: number;
                    } | {
                        /** @enum {string} */
                        kind: "forgotten";
                        /** @default 5 */
                        minPlays?: number;
                        /** @default 90 */
                        idleDays?: number;
                        /** @default 50 */
                        limit?: number;
                    };
                };
            };
        };
        responses: {
            /** @description The picked tracks and a suggested name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        suggestedName: string;
                        tracks: {
                            id: string;
                            name: string;
                            durationMs: number;
                            album: {
                                name: string;
                                thumbUrl: string | null;
                            };
                            artists: components["schemas"]["ArtistRef"][];
                            playCount: number;
                            /**
                             * Format: date-time
                             * @example 2026-09-21T12:00:00.000Z
                             */
                            lastPlayedAt: string | null;
                        }[];
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    listPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your playlists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        playlists: components["schemas"]["PlaylistSummary"][];
                        /**
                         * Format: date-time
                         * @example 2026-09-21T12:00:00.000Z
                         */
                        syncedAt: string | null;
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    createPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string;
                    /** @default [] */
                    trackIds?: string[];
                };
            };
        };
        responses: {
            /** @description The new playlist. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForbiddenError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    addPlaylistItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spotify playlist id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    trackIds: string[];
                    position?: number;
                };
            };
        };
        responses: {
            /** @description Added. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForbiddenError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    removePlaylistItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spotify playlist id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    trackIds: string[];
                };
            };
        };
        responses: {
            /** @description Removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForbiddenError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    movePlaylistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spotify playlist id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    from: number;
                    to: number;
                };
            };
        };
        responses: {
            /** @description Moved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForbiddenError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    syncPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Playlists the user owns or collaborates on. */
                        total: number;
                        /** @description Playlists whose tracks were fetched in this call. */
                        synced: number;
                        /** @description Playlists still waiting for their tracks. */
                        remaining: number;
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForbiddenError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    getPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spotify playlist id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The playlist. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        playlist: {
                            id: string;
                            name: string;
                            description: string | null;
                            imageUrl: string | null;
                            ownerName: string | null;
                            owned: boolean;
                            collaborative: boolean;
                            isPublic: boolean | null;
                            itemCount: number;
                            playsFrom: number;
                            /** @description False until the tracks have been fetched once. */
                            itemsSynced: boolean;
                        };
                        items: components["schemas"]["PlaylistTrack"][];
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getStatsOverview: {
        parameters: {
            query?: {
                /** @description A rolling window ending now. */
                range?: components["schemas"]["StatsRange"];
                /** @description IANA time zone for day boundaries. */
                tz?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        range: components["schemas"]["StatsRange"];
                        tz: string;
                        /** @enum {string} */
                        bucket: "day" | "week";
                        totals: {
                            plays: number;
                            minutes: number;
                            tracks: number;
                            artists: number;
                            newTracks: number;
                        };
                        series: {
                            /** @description Bucket start, YYYY-MM-DD. */
                            date: string;
                            newTracks: number;
                            replays: number;
                            minutes: number;
                        }[];
                        /** @description Unfilled history gaps in the range. */
                        openGaps: number;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getStatsTop: {
        parameters: {
            query?: {
                type?: "tracks" | "artists" | "albums";
                /** @description A rolling window ending now. */
                range?: components["schemas"]["StatsRange"];
                metric?: "plays" | "minutes";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ranking, echoing the query. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @default tracks
                         * @enum {string}
                         */
                        type: "tracks" | "artists" | "albums";
                        range?: components["schemas"]["StatsRange"];
                        /**
                         * @default plays
                         * @enum {string}
                         */
                        metric: "plays" | "minutes";
                        /** @default 10 */
                        limit: number;
                        items: components["schemas"]["TopItem"][];
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getSpotifyTop: {
        parameters: {
            query?: {
                type?: "tracks" | "artists";
                /** @description Spotify's windows: about 4 weeks, 6 months, or a year. */
                timeRange?: "short_term" | "medium_term" | "long_term";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spotify's ranking, echoing the query. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @default tracks
                         * @enum {string}
                         */
                        type: "tracks" | "artists";
                        /**
                         * @description Spotify's windows: about 4 weeks, 6 months, or a year.
                         * @default short_term
                         * @enum {string}
                         */
                        timeRange: "short_term" | "medium_term" | "long_term";
                        items: components["schemas"]["SpotifyTopItem"][];
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForbiddenError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description reauth_required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthRequiredError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
            /** @description rate_limited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedError"];
                };
            };
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new import. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    addImportPlays: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    plays: components["schemas"]["ImportedPlay"][];
                };
            };
        };
        responses: {
            /** @description Plays staged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: number;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description already_finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlreadyFinishedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    finishImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finished. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Tracks queued for a Spotify lookup. */
                        tracksToFetch: number;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"];
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getLatestImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest import. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        import: components["schemas"]["ImportStatus"];
                    };
                };
            };
            /** @description unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
}
