import { createOpenApiHttp } from 'openapi-msw'
import type { paths } from './api.gen.ts'
import {
  devices,
  libraryPage,
  pixelg,
  playback,
  playlistDetail,
  playlistsList,
  playsPage,
  queue,
  searchResponse,
  spotifyTracks,
  spotifyTop,
  statsOverview,
  statsTop,
  trackDetail,
} from './fixtures.ts'

/**
 * MSW's `http`, typed from the API's OpenAPI spec (`api.gen.ts`, generated by
 * `pnpm --filter @replay-crate/web api-types`). Paths use the spec's `{id}` form, and a handler
 * whose path, request or response body doesn't match the API fails `pnpm typecheck`.
 *
 * For a status the spec doesn't declare (a proxy's 502, say) use
 * `({ response }) => response.untyped(new HttpResponse(null, { status: 502 }))`.
 */
export const http = createOpenApiHttp<paths>()

/**
 * A page of `items` the way the API pages them: `limit` and `offset` (numbered pages, which add
 * `total`), or everything at once with no more pages when the app asks by cursor.
 */
export function pageBy<T>(items: T[], query: { get(name: 'offset' | 'limit'): string | null }) {
  const offset = query.get('offset')
  if (offset === null) return { items, rest: {} }
  const start = Number(offset)
  const limit = Number(query.get('limit') ?? 50)
  return { items: items.slice(start, start + limit), rest: { total: items.length }, next: items[start + limit] }
}

/** A signed-in user with some history: every endpoint the app reads answers with fixtures. */
export const handlers = {
  system: [http.get('/api/v1/system/health', ({ response }) => response(200).json({ ok: true }))],
  auth: [
    http.get('/api/v1/auth/me', ({ response }) => response(200).json(pixelg)),
    http.post('/api/v1/auth/logout', ({ response }) => response(204).empty()),
  ],
  history: [
    http.get('/api/v1/history/plays', ({ query, response }) => {
      const { items, rest, next } = pageBy(playsPage.items, query)
      const older = 'total' in rest ? { olderPlayedAt: next?.playedAt ?? null } : {}
      return response(200).json({ ...playsPage, items, ...rest, ...older })
    }),
    http.post('/api/v1/history/sync', ({ response }) =>
      response(200).json({ status: 'skipped', inserted: 0, lastSyncedAt: playsPage.lastSyncedAt!, missedPlays: false }),
    ),
    http.get('/api/v1/history/gaps', ({ response }) => response(200).json({ gaps: [] })),
  ],
  tracks: [
    http.get('/api/v1/tracks', ({ query, response }) => {
      const { items, rest } = pageBy(libraryPage.items, query)
      return response(200).json({ ...libraryPage, ...rest, items })
    }),
    http.get('/api/v1/tracks/{id}', ({ response }) => response(200).json(trackDetail)),
  ],
  playlists: [
    http.get('/api/v1/playlists', ({ response }) => response(200).json(playlistsList)),
    http.get('/api/v1/playlists/{id}', ({ response }) => response(200).json(playlistDetail)),
    http.post('/api/v1/playlists/sync', ({ response }) => response(200).json({ total: 3, synced: 0, remaining: 0 })),
  ],
  stats: [
    http.get('/api/v1/stats/overview', ({ response }) => response(200).json(statsOverview())),
    http.get('/api/v1/stats/top', ({ query, response }) =>
      response(200).json({
        ...statsTop,
        type: (query.get('type') as typeof statsTop.type | null) ?? 'tracks',
        metric: (query.get('metric') as typeof statsTop.metric | null) ?? 'plays',
      }),
    ),
    http.get('/api/v1/stats/spotify-top', ({ response }) => response(200).json(spotifyTop)),
  ],
  imports: [http.get('/api/v1/imports/latest', ({ response }) => response(200).json({ import: null }))],
  // Whatever is typed, the "pete" results (facets only when asked for).
  search: [
    http.get('/api/v1/search', ({ query, response }) => {
      const { facets, ...rest } = searchResponse
      return response(200).json({ ...rest, query: { ...rest.query, text: query.get('q') ?? '' }, ...(query.get('facets') === 'true' && { facets }) })
    }),
    http.get('/api/v1/search/spotify', ({ response }) => response(200).json({ tracks: spotifyTracks })),
  ],
  // Something is playing on the laptop; every command is accepted.
  player: [
    http.get('/api/v1/player', ({ response }) => response(200).json({ playback })),
    http.get('/api/v1/player/queue', ({ response }) => response(200).json(queue)),
    http.get('/api/v1/player/devices', ({ response }) => response(200).json({ devices })),
    ...(['/api/v1/player/play', '/api/v1/player/pause', '/api/v1/player/seek', '/api/v1/player/shuffle', '/api/v1/player/repeat', '/api/v1/player/volume', '/api/v1/player/device'] as const).map((path) =>
      http.put(path, ({ response }) => response(204).empty()),
    ),
    ...(['/api/v1/player/next', '/api/v1/player/previous', '/api/v1/player/queue'] as const).map((path) =>
      http.post(path, ({ response }) => response(204).empty()),
    ),
  ],
}

export const defaultHandlers = Object.values(handlers).flat()
