import { createOpenApiHttp } from 'openapi-msw'
import type { paths } from './api.gen.ts'
import {
  pixelg,
  playlistDetail,
  playlistsList,
  playsPage,
  spotifyTop,
  statsOverview,
  statsTop,
  trackDetail,
} from './fixtures.ts'

/**
 * MSW's `http`, typed from the API's OpenAPI spec (`api.gen.ts`, generated by
 * `pnpm --filter @replay-crate/web api-types`). Paths use the spec's `{id}` form, and a handler
 * whose path, request or response body doesn't match the API fails `pnpm typecheck`.
 *
 * For a status the spec doesn't declare (a proxy's 502, say) use
 * `({ response }) => response.untyped(new HttpResponse(null, { status: 502 }))`.
 */
export const http = createOpenApiHttp<paths>()

/** A signed-in user with some history: every endpoint the app reads answers with fixtures. */
export const handlers = {
  system: [http.get('/api/v1/system/health', ({ response }) => response(200).json({ ok: true }))],
  auth: [
    http.get('/api/v1/auth/me', ({ response }) => response(200).json(pixelg)),
    http.post('/api/v1/auth/logout', ({ response }) => response(204).empty()),
  ],
  history: [
    http.get('/api/v1/history/plays', ({ response }) => response(200).json(playsPage)),
    http.post('/api/v1/history/sync', ({ response }) =>
      response(200).json({ status: 'skipped', inserted: 0, lastSyncedAt: playsPage.lastSyncedAt!, missedPlays: false }),
    ),
    http.get('/api/v1/history/gaps', ({ response }) => response(200).json({ gaps: [] })),
  ],
  tracks: [http.get('/api/v1/tracks/{id}', ({ response }) => response(200).json(trackDetail))],
  playlists: [
    http.get('/api/v1/playlists', ({ response }) => response(200).json(playlistsList)),
    http.get('/api/v1/playlists/{id}', ({ response }) => response(200).json(playlistDetail)),
    http.post('/api/v1/playlists/sync', ({ response }) => response(200).json({ total: 3, synced: 0, remaining: 0 })),
  ],
  stats: [
    http.get('/api/v1/stats/overview', ({ response }) => response(200).json(statsOverview())),
    http.get('/api/v1/stats/top', ({ query, response }) =>
      response(200).json({
        ...statsTop,
        type: (query.get('type') as typeof statsTop.type | null) ?? 'tracks',
        metric: (query.get('metric') as typeof statsTop.metric | null) ?? 'plays',
      }),
    ),
    http.get('/api/v1/stats/spotify-top', ({ response }) => response(200).json(spotifyTop)),
  ],
  imports: [http.get('/api/v1/imports/latest', ({ response }) => response(200).json({ import: null }))],
}

export const defaultHandlers = Object.values(handlers).flat()
