import {
  addPlaylistItems,
  addToQueue,
  createPlaylist,
  exchangeCode,
  getAlbum,
  getArtist,
  getCurrentUser,
  getDevices,
  getMyPlaylists,
  getPlaybackState,
  getPlaylistItems,
  getPlaylistMeta,
  getQueue,
  getRecentlyPlayed,
  getTopArtists,
  getTopTracks,
  getTrack,
  pause,
  play,
  refreshAccessToken,
  removePlaylistItems,
  reorderPlaylistItems,
  seek,
  setRepeat,
  setShuffle,
  setVolume,
  skipToNext,
  skipToPrevious,
  transferPlayback,
} from '@replay-crate/spotify'
import type { SpotifyGateway } from '../deps.ts'

export function createSpotifyGateway(clientId: string): SpotifyGateway {
  return {
    exchangeCode: (params) => exchangeCode({ clientId, ...params }),
    refreshAccessToken: (refreshToken) => refreshAccessToken({ clientId, refreshToken }),
    getCurrentUser: (accessToken) => getCurrentUser(accessToken),
    getRecentlyPlayed: (accessToken) => getRecentlyPlayed(accessToken),
    getPlaylistMeta: (accessToken, id) => getPlaylistMeta(accessToken, id),
    getAlbum: (accessToken, id) => getAlbum(accessToken, id),
    getArtist: (accessToken, id) => getArtist(accessToken, id),
    getMyPlaylists: (accessToken, offset) => getMyPlaylists(accessToken, offset),
    getPlaylistItems: (accessToken, playlistId, offset) => getPlaylistItems(accessToken, playlistId, offset),
    createPlaylist: (accessToken, details) => createPlaylist(accessToken, details),
    addPlaylistItems: (accessToken, playlistId, uris, position) => addPlaylistItems(accessToken, playlistId, uris, position),
    removePlaylistItems: (accessToken, playlistId, uris) => removePlaylistItems(accessToken, playlistId, uris),
    reorderPlaylistItems: (accessToken, playlistId, move) => reorderPlaylistItems(accessToken, playlistId, move),
    getTopTracks: (accessToken, timeRange) => getTopTracks(accessToken, timeRange),
    getTopArtists: (accessToken, timeRange) => getTopArtists(accessToken, timeRange),
    getTrack: (accessToken, id) => getTrack(accessToken, id),
    getPlaybackState: (accessToken) => getPlaybackState(accessToken),
    getQueue: (accessToken) => getQueue(accessToken),
    getDevices: (accessToken) => getDevices(accessToken),
    play: (accessToken, request) => play(accessToken, request),
    pause: (accessToken, target) => pause(accessToken, target),
    skipToNext: (accessToken, target) => skipToNext(accessToken, target),
    skipToPrevious: (accessToken, target) => skipToPrevious(accessToken, target),
    seek: (accessToken, positionMs, target) => seek(accessToken, positionMs, target),
    setRepeat: (accessToken, state, target) => setRepeat(accessToken, state, target),
    setShuffle: (accessToken, on, target) => setShuffle(accessToken, on, target),
    setVolume: (accessToken, percent, target) => setVolume(accessToken, percent, target),
    addToQueue: (accessToken, uri, target) => addToQueue(accessToken, uri, target),
    transferPlayback: (accessToken, deviceId, options) => transferPlayback(accessToken, deviceId, options),
  }
}
